### ISSUE TITLE
duplicate peptide key error

### ISSUE THREAD

**Issue by jj-umn** [compomics/peptide-shaker#260] opened 2017-04-24 14:47 UTC
java.lang.IllegalArgumentException: Attempting to create duplicate peptide key: IMIQHSEMMIEFK_15.99491461956-ATAA-2 from peptide IMIQHSEMMIEFK_15.99491461956-ATAA-2_31.98982923912-ATAA-2.
	at eu.isas.peptideshaker.ptm.PtmScorer.scorePTMs(PtmScorer.java:958)
	at eu.isas.peptideshaker.ptm.PtmScorer.scorePeptidePtms(PtmScorer.java:1466)
	at eu.isas.peptideshaker.PeptideShaker.processIdentifications(PeptideShaker.java:490)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:548)
	at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporter.java:152)
	at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:229)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:735)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:218)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:935)
Free memory: 5735809544

I've trimmed down the input data to 1 MGF and a small number proteins and shared them on google drive: 

https://drive.google.com/drive/folders/0B5gotQcSckTmUTZZc0VFLWljUU0?usp=sharing[https://drive.google.com/drive/folders/0B5gotQcSckTmUTZZc0VFLWljUU0?usp=sharing](url)

I also added some extra printfs to  eu/isas/peptideshaker/ptm/PtmScorer.java to see if I could figure out what was happening:
`                String scans = "\n";
                for (String key : peptideMatch.getSpectrumMatchesKeys()) {                    scans += key + "\n";
                }
                String keys = "\n";
                for (String key : identification.getPeptideIdentification()) {
                    if (key.indexOf("IMIEMDGTENK") >= 0) {
                        keys += key + "\n";
                    }

                }
                System.err.print("Attempting to create duplicate peptide key: " + newKey + " from peptide " + originalKey + " seq:" + peptide.getSequence() + "  \n keys:" + keys + "\n scans:" + scans);
               System.err.print("Attempting to create duplicate peptide key: " + newKey + " from peptide " + originalKey + " seq:" + peptide.getSequence());
                throw new IllegalArgumentException("Attempting to create duplicate peptide key: " + newKey + " from peptide " + originalKey + " seq:" + peptide.getSequence() + "  \n keys:" + keys + "\n scans:" + scans);
            }
`
java.lang.IllegalArgumentException: Attempting to create duplicate peptide key: IMIQHSEMMIEFK_15.99491461956 from peptide IMIQHSEMMIEFK_15.99491461956_31.98982923912-ATAA-2.  
 keys:
IMIEMDGTENKSK_31.98982923912-ATAA-5
IMIEMDGTENKSKFGANAIIGVSIAVCK_15.99491461956-ATAA-2_42.0105646837-ATAA-1
IMIEMDGTENK
IDKIMIEMDGTENK_15.99491461956-ATAA-5_15.99491461956-ATAA-8
IDKIMIEMDGTENK_31.98982923912-ATAA-5_31.98982923912-ATAA-8
IMIEMDGTENKSK_15.99491461956-ATAA-2_15.99491461956-ATAA-5
INVTEQEKIDKIMIEMDGTENK_15.99491461956-ATAA-13
IMIEMDGTENKSK_15.99491461956-ATAA-2_42.0105646837-ATAA-1
IMIEMDGTENK_15.99491461956-ATAA-5_31.98982923912-ATAA-2
IDKIMIEMDGTENKSK_15.99491461956-ATAA-5_15.99491461956-ATAA-8
IMIEMDGTENK_15.99491461956-ATAA-2
IMIEMDGTENK_15.99491461956-ATAA-5
IDKIMIEMDGTENKSK_31.98982923912-ATAA-5
IDKIMIEMDGTENK
IMIEMDGTENKSK
IMIEMDGTENK_31.98982923912-ATAA-2
IMIEMDGTENK_31.98982923912-ATAA-2_42.0105646837-ATAA-1
IMIEMDGTENK_42.0105646837-ATAA-1
IDKIMIEMDGTENK_15.99491461956-ATAA-5
IMIEMDGTENKSKFGAN_31.98982923912-ATAA-2_31.98982923912-ATAA-5_42.0105646837-ATAA-1
IMIEMDGTENK_15.99491461956-ATAA-2_15.99491461956-ATAA-5
IDKIMIEMDGTENK_31.98982923912-ATAA-5_42.0105646837-ATAA-1
IMIEMDGTENK_15.99491461956-ATAA-2_31.98982923912-ATAA-2
IMIEMDGTENKSK_15.99491461956-ATAA-2
IMIEMDGTENKSK_15.99491461956-ATAA-5

 scans:
Mascot formatted MGF of data 27.mgf_cus_tgriffin_cguerrer_20150128_RP_MCF7_ingeldigest_band48kb_replicate3.08013.08013.3
Mascot formatted MGF of data 27.mgf_cus_tgriffin_cguerrer_20150128_RP_MCF7_ingeldigest_band48kb_replicate3.22514.22514.3
Mascot formatted MGF of data 27.mgf_cus_tgriffin_cguerrer_20150128_RP_MCF7_ingeldigest_band48kb_replicate3.07720.07720.3

	at eu.isas.peptideshaker.ptm.PtmScorer.scorePTMs(PtmScorer.java:976)

**Comment by hbarsnes** [comment] 2017-04-26 15:36
Hi JJ,

Thanks for the data. I can confirm that the issue is reproducible on our side when loading your data. Marc will look into it in more detail as soon as he gets the chance.

Best regards,
Harald

**Comment by xthua** [comment] 2017-09-06 15:04
hi, I also met the "Attempting to create duplicate peptide key" problem. 
The error report was listed below:
Wed Sep 06 09:23:13 CST 2017: PeptideShaker version 1.16.13.
Memory given to the Java virtual machine: 74654941184.
Total amount of memory in the Java virtual machine: 163053568.
Free memory: 99549784.
Java version: 1.8.0_141.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_141
os.name: Linux
memory: 75.6/231.2
processors available: 48
useCommandThread: false
<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>
java.lang.IllegalArgumentException: Attempting to create duplicate peptide key: QQKKYKKYEK_79.96633052074999-ATAA-8 from peptide QQKKYKKYEK_144.10206242080005-ATAA-8_79.96633052074999-ATAA-8.
    at eu.isas.peptideshaker.ptm.PtmScorer.scorePTMs(PtmScorer.java:958)
    at eu.isas.peptideshaker.ptm.PtmScorer.scorePeptidePtms(PtmScorer.java:1466)
    at eu.isas.peptideshaker.PeptideShaker.processIdentifications(PeptideShaker.java:490)
    at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:547)
    at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.doInBackground(FileImporter.java:431)
    at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at javax.swing.SwingWorker.run(SwingWorker.java:334)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Free memory: 8571054848
<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>
java.lang.IndexOutOfBoundsException: Index: 86100, Size: 86100
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.get(ArrayList.java:429)
    at com.compomics.util.experiment.io.massspectrometry.MgfIndex.getSpectrumTitle(MgfIndex.java:239)
    at com.compomics.util.experiment.massspectrometry.SpectrumFactory.getSpectrumTitle(SpectrumFactory.java:994)
    at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importSpectrum(FileImporter.java:999)
    at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importPsms(FileImporter.java:720)
    at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:476)
    at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.doInBackground(FileImporter.java:431)
    at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at javax.swing.SwingWorker.run(SwingWorker.java:334)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Free memory: 20215686808
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 7 >= 5
    at java.util.Vector.elementAt(Vector.java:474)
    at javax.swing.table.DefaultTableColumnModel.getColumn(DefaultTableColumnModel.java:294)
    at javax.swing.plaf.basic.BasicTableHeaderUI.paint(BasicTableHeaderUI.java:648)
    at javax.swing.plaf.synth.SynthTableHeaderUI.paint(SynthTableHeaderUI.java:173)
    at javax.swing.plaf.synth.SynthTableHeaderUI.update(SynthTableHeaderUI.java:144)
    at javax.swing.JComponent.paintComponent(JComponent.java:780)
    at javax.swing.JComponent.paint(JComponent.java:1056)
    at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
    at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:290)
    at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
    at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
    at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
    at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
    at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
    at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
    at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
    at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
    at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 7 >= 7
    at java.util.Vector.elementAt(Vector.java:474)
    at javax.swing.table.DefaultTableColumnModel.getColumn(DefaultTableColumnModel.java:294)
    at javax.swing.plaf.basic.BasicTableHeaderUI.paint(BasicTableHeaderUI.java:648)
    at javax.swing.plaf.synth.SynthTableHeaderUI.paint(SynthTableHeaderUI.java:173)
    at javax.swing.plaf.synth.SynthTableHeaderUI.update(SynthTableHeaderUI.java:144)
    at javax.swing.JComponent.paintComponent(JComponent.java:780)
    at javax.swing.JComponent.paint(JComponent.java:1056)
    at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
    at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:290)
    at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
    at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
    at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
    at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
    at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
    at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
    at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
    at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
    at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


Wed Sep 06 15:20:58 CST 2017: PeptideShaker version 1.16.13.
Memory given to the Java virtual machine: 74654941184.
Total amount of memory in the Java virtual machine: 163053568.
Free memory: 125166024.
Java version: 1.8.0_141.
java.lang.IllegalArgumentException: Attempting to create duplicate peptide key: YMFKMYRDK_79.96633052074999-ATAA-6 from peptide YMFKMYRDK_144.10206242080005-ATAA-6_79.96633052074999-ATAA-6.
    at eu.isas.peptideshaker.ptm.PtmScorer.scorePTMs(PtmScorer.java:958)
    at eu.isas.peptideshaker.ptm.PtmScorer.scorePeptidePtms(PtmScorer.java:1466)
    at eu.isas.peptideshaker.PeptideShaker.processIdentifications(PeptideShaker.java:490)
    at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:547)
    at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporter.java:151)
    at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:229)
    at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:735)
    at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:218)
    at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:935)
Free memory: 4662478408


Wed Sep 06 21:57:34 CST 2017: PeptideShaker version 1.16.13.
Memory given to the Java virtual machine: 74654941184.
Total amount of memory in the Java virtual machine: 163053568.
Free memory: 102365464.
Java version: 1.8.0_141.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_141
os.name: Linux
memory: 75.9/231.2
processors available: 48
useCommandThread: false


Wed Sep 06 22:01:08 CST 2017: PeptideShaker version 1.16.13.
Memory given to the Java virtual machine: 74654941184.
Total amount of memory in the Java virtual machine: 163053568.
Free memory: 102668736.
Java version: 1.8.0_141.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_141
os.name: Linux
memory: 75.7/231.2
processors available: 48
useCommandThread: false
<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>
java.lang.IllegalArgumentException: Attempting to create duplicate peptide key: QQKKYKKYEK_79.96633052074999-ATAA-8 from peptide QQKKYKKYEK_144.10206242080005-ATAA-8_79.96633052074999-ATAA-8.
    at eu.isas.peptideshaker.ptm.PtmScorer.scorePTMs(PtmScorer.java:958)
    at eu.isas.peptideshaker.ptm.PtmScorer.scorePeptidePtms(PtmScorer.java:1466)
    at eu.isas.peptideshaker.PeptideShaker.processIdentifications(PeptideShaker.java:490)
    at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:547)
    at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.doInBackground(FileImporter.java:431)
    at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at javax.swing.SwingWorker.run(SwingWorker.java:334)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Free memory: 11109549760
<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>
java.lang.IllegalArgumentException: OMSSA modification indexes not set in the search parameters.
    at eu.isas.peptideshaker.fileimport.PsmImporter.hasPotentialTerminalModification(PsmImporter.java:747)
    at eu.isas.peptideshaker.protein_inference.PeptideMapper.getPeptideMap(PeptideMapper.java:425)
    at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importPsms(FileImporter.java:743)
    at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:476)
    at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.doInBackground(FileImporter.java:431)
    at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at javax.swing.SwingWorker.run(SwingWorker.java:334)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Free memory: 32406873680

**Comment by hbarsnes** [comment] 2019-11-22 13:37
This issue should be solved in the new beta releases of SearchGUI and PeptideShaker. Please see https://groups.google.com/forum/#!topic/peptide-shaker/1ecY0IyMOBM for more details.

If the issue still exists in the beta releases, please open a new issue at https://github.com/compomics/peptide-shaker-2.0-issue-tracker/issues.

If the issue has been solved, it would also be great of you could let us know by replying to this original issue and letting us know. :)

**Comment by hbarsnes** [comment] 2020-11-04 21:15
This issue should hopefully be fixed in the new release that is available now. If not, please let us know by opening a new issue.

**Closed by hbarsnes** 2020-11-04 21:15 UTC
Labels: bug
