### ISSUE TITLE
PeptideShaker freezes 

### ISSUE THREAD

**Issue by CarlaCristinaUranga** [compomics/peptide-shaker#403] opened 2020-05-20 19:04 UTC
Hi, I have been running peptide shaker successfully, however all of a sudden the program is freezing after unzipping the identification file. I have attached the output log, no error is reported, it just freezes and the server status. I should mention I am using msgf. Previously it worked with myrimatch.

[C1_msgf.log](https://github.com/compomics/peptide-shaker/files/4658685/C1_msgf.log)

**Comment by hbarsnes** [comment] 2020-05-24 12:09
Try unzipping the file manually to see if it is corrupt. You can also try loading the data on your laptop just to see if you immediately get an error there as well. At least then you know if the problem is the server or not.

**Comment by hbarsnes** [comment] 2020-11-04 20:56
This issue should hopefully be fixed in the new release that is available now. If not, please let us know by opening a new issue.

**Closed by hbarsnes** 2020-11-04 20:56 UTC
Labels: help wanted
