### ISSUE TITLE
Cross-platform support for locating missing data files

### ISSUE THREAD

**Issue by cdlawless** [compomics/peptide-shaker#175] opened 2016-05-27 11:48 UTC
Hi Guys

I wanted to benchmark andromeda for some of our analysis. Ran Andromeda via SearchGUI (2.8.6) on windows, set output to zip to include spectra and fasta files. Moved zip file to our HPC (linux) and ran PeptideShakerCLI (as follows):

java -Xms1024m -Xmx262144m -cp /mnt/lustre/mjfidcl2/PeptideShaker-1.10.2/PeptideShaker-1.10.2.jar  eu.isas.peptideshaker.cmd.PeptideShakerCLI -experiment MDV3_andromeda_10 -sample MDV3_andromeda_10_sampl
e -replicate 1 -identification_files "/mnt/fls01-home01/mjfidcl2/scratch/DDIP/FDR_Comparison/SearchGUI/searchGUI_zips/searchgui_mdv3_andromeda_10.zip" -out "/mnt/fls01-home01/mjfidcl2/scratch/DDIP/FDR_Co
mparison/SearchGUI/PS_Projects/MDV3_Andromeda_10.cpsx" -ptm_score 1 -zip "/mnt/lustre/mjfidcl2/DDIP/FDR_Comparison/SearchGUI/PS_zips/MDV3_Andromeda_10.zip" -temp_folder "/mnt/lustre/mjfidcl2/DDIP/FDR_Com
parison/SearchGUI/temp"

It fails to proceed once the zip file has been extracted.
Path configuration completed.
Fri May 27 12:44:08 BST 2016 Unzipping searchgui_mdv3_andromeda_10.zip.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%

Fri May 27 12:44:26 BST 2016 FASTA file 'C:\Users\mjfidcl2\Google Drive\Dropbox\slola_proteome_MDV3_v1.1_concatenated_target_decoy.fasta' not found.
Fri May 27 12:44:26 BST 2016 Import process for MDV3_andromeda_10 (Sample: MDV3_andromeda_10_sample, Replicate: 1)

Fri May 27 12:44:27 BST 2016 Importing sequences from C:\Users\mjfidcl2\Google Drive\Dropbox\slola_proteome_MDV3_v1.1_concatenated_target_decoy.fasta.
Fri May 27 12:44:27 BST 2016 File C:\Users\mjfidcl2\Google Drive\Dropbox\slola_proteome_MDV3_v1.1_concatenated_target_decoy.fasta was not found. Please select a different FASTA file.
Fri May 27 12:44:27 BST 2016 PeptideShaker Processing Canceled.
<CompomicsError>PeptideShaker processing canceled. See the PeptideShaker log for details.</CompomicsError>

File C:\Users\mjfidcl2\Google Drive\Dropbox\slola_proteome_MDV3_v1.1_concatenated_target_decoy.fasta was not found. Please select a different FASTA file.
java.io.FileNotFoundException: The FASTA file '/net/lustre/mjfidcl2/DDIP/FDR_Comparison/SearchGUI/C:\Users\mjfidcl2\Google Drive\Dropbox\slola_proteome_MDV3_v1.1_concatenated_target_decoy.fasta' could no
t be found!
    at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.loadFastaFile(SequenceFactory.java:536)
    at eu.isas.peptideshaker.fileimport.FileImporter.importSequences(FileImporter.java:174)
    at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:448)
    at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporter.java:156)
    at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:232)
    at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:696)
    at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:205)
    at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:908)

Is this an issue from Windows->linux? or is SearchGUI not rewriting the parameter file correctly for the zip file?

Kind Regards

Craig

**Comment by hbarsnes** [comment] 2016-05-28 09:08
Hi Craig,

The problem seems to be the move from Windows to Linux and the use of opposite path separators. This results in "C:\Users\mjfidcl2\Google Drive\Dropbox\slola_proteome_MDV3_v1.1_concatenated_target_decoy.fasta" ending up as the assumed file name on Linux (instead of just "slola_proteome_MDV3_v1.1_concatenated_target_decoy.fasta"), and we therefore start looking for the FASTA file in "/net/lustre/mjfidcl2/DDIP/FDR_Comparison/SearchGUI/C:\Users\mjfidcl2\Google Drive\Dropbox\slola_proteome_MDV3_v1.1_concatenated_target_decoy.fasta", which is of course not a valid path.

We will try to find a workaround. Will most likely happen to other files as well.

Best regards,
Harald

**Comment by hbarsnes** [comment] 2017-05-19 13:12
Hi Craig,

Maybe this got solved in later versions and I just forgot to tell you and close the issue, but I just tested running a SearchGUI search on Linux and then processing the zip file in PeptideShaker on Windows and it worked without any problems, both in the GUI and on the command line. 

Do you still have this problem on your side? If so, could you share the zip file with me so that I can try to reproduce it on my end?

Best regards,
Harald

**Closed** 2017-12-12 13:20 UTC
Labels: bug
