### ISSUE TITLE
Attempting to create duplicate peptide key

### ISSUE THREAD

**Issue by pvstodghill** [compomics/peptide-shaker#200] opened 2016-08-18 12:53 UTC
When running PeptideShaker with the following invocation,

```
java -Djava.awt.headless=true -d64 -Xms512m -Xmx16g \
   -cp .../PeptideShaker-1.13.0.jar \
   eu.isas.peptideshaker.cmd.PeptideShakerCLI \
   -threads 1
   -experiment experiment -sample sample -replicate 1 \
   -identification_files work/searchruns/4.searchgui_out.zip \
   -spectrum_files work/spectra \
   -id_params work/params.par
   -out work/peptideshaker_out.cpsx
```

I get the following error.

```
Wed Aug 17 15:36:43 EDT 2016 Attempting to create duplicate peptide key: NAQMAEKPVVSMPSSTIK_15.99491461956 from peptide NAQMAEKPVVSMPSSTIK_15.99491461956-ATAA-12.
java.lang.IllegalArgumentException: Attempting to create duplicate peptide key: NAQMAEKPVVSMPSSTIK_15.99491461956 from peptide NAQMAEKPVVSMPSSTIK_15.99491461956-ATAA-12.
    at eu.isas.peptideshaker.ptm.PtmScorer.scorePTMs(PtmScorer.java:974)
    at eu.isas.peptideshaker.ptm.PtmScorer.scorePeptidePtms(PtmScorer.java:1482)
    at eu.isas.peptideshaker.PeptideShaker.processIdentifications(PeptideShaker.java:496)
    at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:559)
    at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporter.java:158)
    at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:234)
    at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:726)
    at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:218)
    at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:939)
```

Input files and full execution output have already been sent to
developer.

Thanks for your help!

**Comment by mvaudel** [comment] 2016-08-18 12:57
Thanks for creating the issue! As said I will be looking into this soon :)

Apologies for the inconvenience,

Marc

**Comment by paulstodghill** [comment] 2016-08-18 14:49
Another bit of information. I re-analyzed the larger data-set (4 spectra files) using only Comet, and PeptideShaker ran to completion without error. I assume that the the single spectra file that I sent to you, if reanalyzed with only Comet would run successfully too.

**Comment by akwalker** [comment] 2016-10-28 21:50
I had the same problem and found that if I set "Confident Sites" to NO (in the  "site alignment" in the PTM scoring section under advanced settings), the data would import successfully.

**Comment by hbarsnes** [comment] 2016-12-08 00:17
Duplicate of issue https://github.com/compomics/peptide-shaker/issues/56. This issue has therefore been closed and instead merged into issue https://github.com/compomics/peptide-shaker/issues/56. Please follow the older issue for updates.

**Closed by hbarsnes** 2016-12-08 00:17 UTC
Labels: bug
