### ISSUE TITLE
mzidentML result export hang-up

### ISSUE THREAD

**Issue by SimionKreimer** [compomics/peptide-shaker#208] opened 2016-10-03 00:28 UTC
I imported 43 MSGF+ result files into PeptideShaker, which took several hours with 50 GB allotted memory. Now I'm trying to export the combined results as a mzidentML file to make a Skyline library, but the process got to 83% and has been stuck for 6 hours now, there is a 1.9 GB mzid file generated and the time stamp updates every hour or so without a noticeable change in size. PeptideShaker is using 80% CPU capacity and all 50 GB of memory and I'm a bit confused about why exporting the results uses up so many resources.

**Comment by mvaudel** [comment] 2016-10-03 08:06
Hi Simion,

Sorry to hear that you are experiencing issues. From what you describe it seems to be a thread lock happening when interacting with the back-end database. I am however unsure where/how this happened. Which version are you working with? Are you working from the gui or using the command line?

Best regards and apologies for the inconvenience,

Marc

**Comment by SimionKreimer** [comment] 2016-10-03 16:56
I'm using the GUI PeptideShaker version 1.13.4 in ArchLinux. I was also experiencing a similar issue in Windows 7 with GUI version 1.13.1. I was able to save the PeptideShaker project and put it in this DropBox folder along with other potentially useful files: https://www.dropbox.com/sh/av7t6yz7zk3n9hu/AADenc80E02rdhVRp_Zyeoi1a?dl=0

**Comment by SimionKreimer** [comment] 2016-10-03 18:36
Minor update, I tried it again with the same data and the progress is stuck on 86%, interestingly the CPU usage is only at 3%, but the memory usage is maximal. PeptideShaker doesn't seem to be using the swap partition, but it may be because I limited the memory at 60GB. If I go higher on the RAM limit (64 GB is what's available on the system) would it use the swap and finish the conversion or will my PC blow up?

**Comment by mvaudel** [comment] 2016-10-03 21:50
Hi again,
There is very little chance of PC blow-up. In the worse case it will become very slow :) PeptideShaker should start swapping as soon as it reaches the maximum limit. And I don't see how exporting these data would need 60 GB of RAM. There must be something wrong going on. I currently have few other bugs to fix but we will hopefully have time to look into this memory issue soon :)
Best regards and sorry again for the issue,
Marc

**Comment by SimionKreimer** [comment] 2016-10-06 21:52
Another minor update which might be helpful. I was able to get around the memory leak by importing and exporting half of the files at a time. Not quiet ideal, but it's ok. However now that I'm trying to import the mzidML results into Skyline-daily on a different system it seems to hang up at 2.5 GB memory and 25% CPU (it might be the maximum for this system). BlibBuild.exe is taking up the resources but doesn't seem to be moving forward according to the progress bar, maybe there's a problematic mzidML related library messing up both PeptideShaker and Skyline?

**Comment by hbarsnes** [comment] 2016-10-07 09:18
Hi Simion,

Thanks for the update. However we're not using any external libraries when reading or writing mzIdentML files. I guess the common factor is the size of the mzIdentML files. As there are many tools that get into problems when these files get too big.

This should not be a problem with our code though. Especially not for the writing of mzIdentML, as this is simply writing one line at the time. So it's most likely a memory or threading issue in our code for parsing the information to write. We'll look into it and get back to you as soon as possible. In the meantime you may consider contacting Skyline about the parsing of the files on their end?

Best regards,
Harald

**Comment by uburra** [comment] 2017-06-15 06:27
Has the abovesaid bug been fixed because I have been trying to export my cpsx files to mzid and the export hangs at 74%.

**Comment by hbarsnes** [comment] 2017-06-15 11:33
> Has the abovesaid bug been fixed because I have been trying to export my cpsx files to mzid and the export hangs at 74%.

We haven't been able to reproduce the issue on our side, which makes it a bit difficult to fix. But if you have a dataset where the issue occurs that you would be willing to share with us we can have a closer look.

Best regards,
Harald

**Comment by sudeep71** [comment] 2017-08-04 15:57
I am facing a simlar issue while exporting peptideshaker data. The progress bar is stuck at 73% for more than 12 hrs. A output file (mzid) is made but i am sure if i kill the process, the file might just be corrupt.
I am using version 1.16.12, on a Ubuntu box.

**Comment by hbarsnes** [comment] 2019-11-22 13:36
This issue should hopefully be solved in the new beta releases of SearchGUI and PeptideShaker. Please see https://groups.google.com/forum/#!topic/peptide-shaker/1ecY0IyMOBM for more details.

If the issue still exists in the beta releases, please open a new issue at https://github.com/compomics/peptide-shaker-2.0-issue-tracker/issues.

If the issue has been solved, it would also be great of you could let us know by replying to this original issue and letting us know. :)

**Comment by hbarsnes** [comment] 2020-11-04 21:17
This issue should hopefully be fixed in the new release that is available now. If not, please let us know by opening a new issue.

**Closed by hbarsnes** 2020-11-04 21:17 UTC
Labels: bug
