### ISSUE TITLE
Syntax error: Encountered "s" at line 1, column 225

### ISSUE THREAD

**Issue by FazeH** [compomics/peptide-shaker#132] opened 2016-02-05 16:00 UTC
Hi ,
I searched my .mgf files using comet+xtandem+MSgfplus. The searches were done with no errors. But I have encountered a new error (Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException) in the post processing step. 

I have attached the bug report for your consideration. 
[PeptideShaker_1.7.1_log.txt](https://github.com/compomics/peptide-shaker/files/119408/PeptideShaker_1.7.1_log.txt)
Thanks
HFaz

**Comment by mvaudel** [comment] 2016-02-05 16:10
Hi HFaz,

It seems that the tool cannot write in its back-end database. Can you make sure that no other instance of PeptideShaker is running? This would lock the back-end database. It can be that the tool crashed and did not release the access to the database, in which case killing the previous instance or restarting the computer would resolve the problem. Please also make sure that the tool has writing access to the folder where it is located.

Hope this helps,

Marc

**Comment by FazeH** [comment] 2016-02-05 16:30
Thanks Marc for your quick reply. 
I have only one instance of PS running and I am sure that it has writing access to its folder. I have to say that I have been testing PS on our local cluster. I use X11-XQuartz forwarding for GUI of PS from my mac (through ssh -X login@cluster). I will test the searchgui_out.zip on my local machine and let you know about the outcome. 
Hope this makes sense.
HFaz

**Comment by mvaudel** [comment] 2016-02-05 17:05
Hi,

If PeptideShaker was not localized on the same system as the one you used
it could have created some issues yes, especially if the OS was not the
same. Please keep us posted with how the testing goes!

Best regards,

Marc

2016-02-05 17:30 GMT+01:00 Hossein Fazelinia <notifications@github.com>:

**Comment by FazeH** [comment] 2016-02-07 04:24
Hi,
I used PS on my Mac to run the searchgui_out.zip that I obtained from our cluster (linux based).  It failed and I don't think the failure is because of the mismatch between OS of different platforms.  Here is the tail of the PS report from my Mac:

Sat Feb 06 15:37:53 EST 2016        Note: a group can present combinations of these criteria.
Sat Feb 06 15:37:53 EST 2016        Generating peptide map.
Sat Feb 06 15:39:28 EST 2016        Computing peptide probabilities.
Sat Feb 06 15:39:28 EST 2016        Saving peptide probabilities.
Sat Feb 06 15:39:30 EST 2016        Generating protein map.
Sat Feb 06 15:39:35 EST 2016        Resolving protein inference issues, inferring peptide and protein PI status.
Sat Feb 06 16:07:02 EST 2016        Importing Data Canceled!
Sat Feb 06 16:07:02 EST 2016        An error occurred while loading the identification files:
Sat Feb 06 16:07:02 EST 2016        Syntax error: Encountered "s" at line 1, column 225.

The error seems to happen during "Resolving protein inference issues".  This is very similar to what I saw in local cluster. In both cases (cluster vs. Mac) the error is "java.sql.SQLSyntaxErrorException: Syntax error: Encountered "s" at line 1, column 225." In both cases I only have one instance of PS. 
I'd greatly appreciate it if you could look into it. I can also send you the necessary files if you are interested.
Thanks
HFaz

**Comment by hbarsnes** [comment] 2016-02-07 12:54
Hi HFaz,

It would be great if you could send us the data your are trying to load in PeptideShaker. Then we will check if we're able to reproduce the error on our side. In addition to the search result file(s) we'll also need the mgf and FASTA files.

Best regards,
Harald

**Comment by FazeH** [comment] 2016-02-07 16:10
Thank you Herald and Marc for your constant support. 
I shared a dropbox folder with you that contains the necessary files.
HFaz

**Comment by hbarsnes** [comment] 2016-02-07 21:45
Hi HFaz,

As far as I can see the shared folder does not contain the searchgui_out.zip file? Without this one we cannot test if we can reproduce the error. From which search engine are you loading data when the processing fails?

BTW, in the future I'd recommend putting all the files in a single zip file and sharing it as a Dropbox link instead of sharing the Dropbox folder directly. Given that when sharing folders one requires that the other person has enough space on his/her Dropbox to access the files. Which is not always the case for big MS datasets. :)

Best regards,
Harald

**Comment by FazeH** [comment] 2016-02-07 22:04
Thanks Herald for your reply. Here is the link for searchgui_out.zip file.
https://www.dropbox.com/s/h0iqkhmpst1glak/searchgui_out.zip?dl=0
I am using a combination of X-tandem, MSGF+, and comet for my searches. 
HFaz

**Comment by hbarsnes** [comment] 2016-02-07 22:24
Hi HFaz,

The all I'm missing is a link to a zip file with all the mgf files and I'm ready to start testing. :)

Best regards,
Harald

**Comment by FazeH** [comment] 2016-02-07 22:30
Here is the link to mgf files: https://www.dropbox.com/sh/n8ixfnafeyh0i5v/AADs-xK8gD9BNqZPRlNjAor5a?dl=0
and the link to the sequence file in case you need it: https://www.dropbox.com/sh/u3s2lsbpa50mfbp/AAARmOWETkOhC_hZ-st55eVda?dl=0
Thank you again for all your help and I look forward to hearing from you.
HFaz

**Comment by hbarsnes** [comment] 2016-02-07 22:33
Hi HFaz,

There are only three mgf files in that zip file (and now it's no longer there?), while your  searchgui_out.zip file refers to eight?

And btw, it's "Harald" not "Herald". :)

Best regards,
Harald

**Comment by FazeH** [comment] 2016-02-07 23:54
Hi Harald,
I think files were being uploaded when I emailed you the link. Here is the link again: https://www.dropbox.com/sh/n8ixfnafeyh0i5v/AADs-xK8gD9BNqZPRlNjAor5a?dl=0
You can find all 8 mgf files here. 
I apologize for the typo in your name in my previous comments.
HFaz

**Comment by hbarsnes** [comment] 2016-02-08 14:57
Hi HFaz,

I think I located the problem and it seems to come from this header in your FASTA file: >generic|pp,CON_ENO1_YEAST,ENO1_YEAST Enolase 1 - Saccharomyces cerevisiae (Baker's yeast)

The problem is the single quote in "Baker's yeast", as it ends up closing an SQL call too early and thus resulting in an SQL syntax error. This would not have been a problem if "Baker's yeast" was part of the protein description, but in your case it's part of the protein accession.

The good news is that is should be easy to fix and that you should not have to redo the searches. In order to enable the loading of this protein header do the following: 1) edit the original FASTA file and either replace/remove the single quote or add a pipe to separate the accession from the description. 2) re-add the decoys, and 3) use this new database when loading the data in PeptideShaker.

Unless you have other FASTA headers causing similar problems (which a quick check seems to indicate that you don't), I think this should allow you to load the data.

Let me know how it goes.

Best regards,
Harald

**Comment by FazeH** [comment] 2016-02-08 15:43
Hi Harald,
Thanks you for dissecting this and finding the issue. I will test it and let you know about the results.
Regards,
HFaz

**Comment by hbarsnes** [comment] 2016-02-20 12:00
Hi HFaz,

I didn't hear back from you, so I will assume that you managed to fix the problem and I'll therefore close this issue. If this is not the case, please let us know and we'll reopen the issue.

Best regards,
Harald

**Closed by hbarsnes** 2016-02-20 12:00 UTC
Labels: help wanted
