### ISSUE TITLE
Error importing PSMs

### ISSUE THREAD

**Issue by armonyG** [compomics/peptide-shaker#271] opened 2017-06-11 09:27 UTC
Hello,
I ran MyriMatch and MS-GF+ from searchGUI (3.2.19)
The search seemed to go fine when searchGUI called Peptide shaker (1.16.10) I got the following error:
```
Sun Jun 11 11:27:50 IDT 2017        Importing PSMs from FS1_DFAS_ECM-CL_deglycosylated_TFMS_1_290517_170604142329.msgf.mzid
Sun Jun 11 11:27:51 IDT 2017        An error occurred: null
Sun Jun 11 11:27:51 IDT 2017        Please contact the developers (https://github.com/compomics/peptide-shaker/issues).
```
I tried opening the search results with a previous version of PeptideShaker (1.14.6) and got a similar error. It did pop up a notification that some modifications have changed (the variable modifications I used for the search) and I should review them. I added a custom modification to this search.
Any ideas of what I can do?

Gadi

**Comment by hbarsnes** [comment] 2017-06-11 12:49
Hi Gadi,

Thanks for telling us about this. Could you send us the PeptideShaker log file? You'll find it via the PeptideShaker Welcome dialog > Settings & Help > Help > Bug Report. This should tell us a bit more about what it going on.

Best regards,
Harald

**Comment by armonyG** [comment] 2017-06-11 14:03
[PeptideShaker 1.16.10 log.txt](https://github.com/compomics/peptide-shaker/files/1066470/PeptideShaker.1.16.10.log.txt)

Does it have something to do with the modification I added?
Here is how the modification I added looks like:
![image](https://user-images.githubusercontent.com/23078645/27011614-ddc91b16-4ec7-11e7-9fa2-1caae78a6cfd.png)

**Comment by hbarsnes** [comment] 2017-06-11 14:25
Hi Gadi,

The issue could be related to the custom PTM, but this is not clear from the log file. Would it be possible for you to share with me the data you are trying to load in PeptideShaker so that I can try to reproduce the error on my side? I would need the SearchGUI results zip file plus the mgf and FASTA file.

Best regards,
Harald

**Comment by armonyG** [comment] 2017-06-11 14:30
Sure, where should I send you the links to the files?

**Comment by hbarsnes** [comment] 2017-06-11 14:34
Hi Gadi,

You can send them to me directly at harald.barsnes@gmail.com.

Best regards,
Harald

**Comment by hbarsnes** [comment] 2017-06-11 16:09
Hi Gadi,

Thanks for the files. I can confirm that the issue is reproducible on my end. I will need to dig a bit deeper and get back to you.

Regarding your custom PTM, have you tried setting it up without the glyco pattern? In other words, just targeting N similar to the other glyco PTMs? The advanced pattern option is still more of a beta feature, and not as thoroughly tested as the normal PTMs.

> BTW this data was collected with both HCD and ETD. Is there a way to search both b+y and c+z at the same time?

As far as I can remember this is not supported by any of the search engines, and hence we cannot provide it as an option in SearchGUI. Not sure what you mean by "collected with both HCD and ETD" though? As in that your mgf files contain MS2 spectra from both HCD and ETD? Sounds like something the search engines would have a hard time interpreting?

Best regards,
Harald

**Comment by armonyG** [comment] 2017-06-11 16:23
I have tried to set it up as only N but couldn't get it to accept just N. Now I managed somehow to get it to accept just N as the modification site so I am running the search again.

The collection method have a decision tree of when to use HCD, when to use ETD, or when to use both.
So some spectra have both b+y and c+z ions but most of them have only b+y so I can use these.

**Comment by armonyG** [comment] 2017-06-12 06:20
Chaining the modification site from NX[ST]X to N did the trick, I can browse the results in peptide shaker.
Thanks for your help!

**Comment by hbarsnes** [comment] 2017-06-12 09:01
Hi Gadi,

Great! I will close this issue then. But we'll hopefully soon make it work with the pattern PTMs as well.

Best regards,
Harald

**Closed by hbarsnes** 2017-06-12 09:01 UTC
Labels: bug
