### ISSUE TITLE
No peptide fraction information, but high protein confidence

### ISSUE THREAD

**Issue by tivdnbos** [compomics/peptide-shaker#366] opened 2019-07-13 20:46 UTC
Hi all,

I ran into a problem, but I couldn't find any answer. I analyzed multiple SearchGUI (.zip) files in PeptideShaker, and handled them as different fractions. 
8 proteins are identified as confident, but the number of peptides, spectra and intensities are 0 in the different fractions. This in both the GUI (see screenshot for example) and the fractions export file.
Do you have any idea what the reason could be?

Best wishes,
Tim

![GUI_confirmation](https://user-images.githubusercontent.com/13612447/61176364-e3c22980-a5bf-11e9-9ead-53acda3f0772.png)

**Comment by hbarsnes** [comment] 2019-07-15 11:38
Hi Tim,

Seems to be a bug, but not sure where. Are all the plots in the Fractions tab empty or just the Peptides plot?

Would it be possible for you to export the project as a zip file and share it with me?

Best regards,
Harald

**Comment by tivdnbos** [comment] 2019-07-15 16:19
Hi Harald,

The first three tabs are empty, the latter three aren't. I have sended you the individual searchgui output files, the database and the parameter file (the cpsx was too large for wetransfer).

Thanks for checking it!
Tim

**Comment by hbarsnes** [comment] 2019-07-15 20:01
Hi Tim,

Thanks for sharing the files. I would however also need all of the mgf files in order to reprocess the data and reproduce the issue. Perhaps you can try to reproduce the issue in a smaller subset of your data that would be easier to share? Or does it only happen when you load all of the datasets at once?

Best regards,
Harald

**Comment by tivdnbos** [comment] 2019-07-16 12:47
Hi Harald,

I send you three fractions, including cpsx file and mgfs. In this smaller subset, I have the same problem with P0DOX6. 
However, this time, I received an error while clicking (the first time) on the fractions tab. Maybe it has something to do with this (see screenshot below).

Best wishes,
Tim 

![probleem3](https://user-images.githubusercontent.com/13612447/61295505-79380600-a7d8-11e9-87e1-6c5d8f72bfad.png)

**Comment by hbarsnes** [comment] 2019-07-17 10:10
Hi Tim,

To open the project I would also need the FASTA file used. I tried using the one from the previous files you shared (Swissprot-human_trypsin_apr18_concatenated_target_decoy.fasta), which has the correct file name, but I get an error due to "Protein not found: P02768". Do you have two FASTA files with the same name but with slightly different content..?

BTW, the best/correct way to share a PeptideShaker project, which ensures that all the required files are included, is to use Export > PeptideShaker Project As > Zip File. :)

Best regards,
Harald

**Comment by tivdnbos** [comment] 2019-07-17 14:35
Thanks for the export tip. I've sended you the export zip file - including database.
However, I used the same database as I've send before, so it's strange that it got this error. I checked the fasta file itself and it's in there (serum albumin).

**Comment by hbarsnes** [comment] 2019-07-17 14:44
> I've sended you the export zip file - including database.

Thanks for the zip file. This one I can load without any issues. However, there are no issue in the Fractions tab either...

**Comment by tivdnbos** [comment] 2019-07-17 15:15
Hmm, I still got some issues...
For example, I go to the fraction tab (on the right) and search for e.g. P04439, or P0DOX6, I get the following results from the plots:
- no information for peptides, spectra and intensities (however confidently identified)
- sequence coverage looks good
- Fractions plot (sun of all peptides in all proteins for the three fractions? - looks good, but didn't check this in detail)
- Expected Molecular weight is the same for all proteins.. and I got, well, an "odd" looking boxplot :)

Can you check the abovementioned proteins?

**Comment by hbarsnes** [comment] 2019-07-17 20:49
> for e.g. P04439, or P0DOX6, I get the following results from the six plots:
no information for peptides, spectra and intensities tab (however confidently identified)

Ah, I only tried some random proteins to see that the plots where not empty. But I can confirm that I also have empty plots for those two proteins. Will have a closer look tomorrow.

> Fractions plot (sum of all peptides in all proteins for the three fractions?

Yes, I think that is correct.

> Expected Molecular weight plot is the same for all proteins.. and I got, well, an "odd" looking boxplot :)

Well, I agree that they look a bit odd, but I don't think there is anything technically wrong with them? :)

**Comment by tivdnbos** [comment] 2019-07-18 09:23
> Ah, I only tried some random proteins to see that the plots where not empty. But I can confirm that I also have empty plots for those two proteins. Will have a closer look tomorrow.

Thanks!
 
> > Expected Molecular weight plot is the same for all proteins.. and I got, well, an "odd" looking boxplot :)
> 
> Well, I agree that they look a bit odd, but I don't think there is anything technically wrong with them? :)

There's nothing technically wrong with them, I even like it ;)

**Comment by hbarsnes** [comment] 2019-07-18 11:49
I had a closer look and the fraction values simply seem to be missing for those two proteins, hence the problem is not the plot itself but rather the lack of data to plot. I'm leaning toward a multi threading issue with the backend database. We've recently reimplemented the whole backend to try to solve such issues.

Researching and reloading now to see if the same proteins go missing. Then I will try in the beta version of PeptideShaker with the new backend. Will keep you posted.

PS: I'd recommend checking the way you generate your FASTA file as it also contains Neanderthal (Homo sapiens neanderthalensis) sequences...

**Comment by hbarsnes** [comment] 2019-07-18 12:17
Update: I get the same proteins missing when reloading in the current release. So maybe not a multi threading issue after all. However, I do not see the same issue with the new beta version. Came across some other Fraction tab related issues instead though.

In order to not waste time debugging the old version I think I will focus on the new beta version and try to get that one working the way it should. I will let you know when it's available for testing.

**Comment by hbarsnes** [comment] 2019-07-18 15:08
After some debugging the dataset now loads fine in the new beta version of PeptideShaker and the Fraction tab seems to work fine. :)

I'll let you know when the beta version is available for testing.

**Comment by hbarsnes** [comment] 2019-11-22 13:53
This issue should be solved in the new beta releases of SearchGUI and PeptideShaker. Please see https://groups.google.com/forum/#!topic/peptide-shaker/1ecY0IyMOBM for more details.

If the issue still exists in the beta releases, please open a new issue at https://github.com/compomics/peptide-shaker-2.0-issue-tracker/issues.

If the issue has been solved, it would also be great of you could let us know by replying to this original issue and letting us know. :)

**Comment by hbarsnes** [comment] 2020-11-04 21:02
This issue should hopefully be fixed in the new release that is available now. If not, please let us know by opening a new issue.

**Closed by hbarsnes** 2020-11-04 21:02 UTC
Labels: bug
