### ISSUE TITLE
Getting StringIndexOutOfBoundsException with PeptideShakerCLI

### ISSUE THREAD

**Issue by max-l** [compomics/peptide-shaker#197] opened 2016-08-10 21:28 UTC
Hello, PeptideShakerCLI is crashing with the following stack trace (see below)

I can provide the input file if that is of any help

Out of  5188 runs of peptideshakerCLI, I get 946 such failures

```
Mon Aug 08 22:48:40 EDT 2016 Importing PSMs from j7497.comet.pep.xml
10% 20% 30% 40% 50% 60% 70% 80% 90%
Mon Aug 08 22:49:22 EDT 2016 336 identified spectra (3.3%) did not present a valid peptide.
Mon Aug 08 22:49:22 EDT 2016 21144 of the best scoring peptides were excluded by the import filters:
Mon Aug 08 22:49:22 EDT 2016     - 37.0% peptide length less than 8 or greater than 30.
Mon Aug 08 22:49:22 EDT 2016     - 62.8% peptide presenting high mass or isotopic deviation.
Mon Aug 08 22:49:22 EDT 2016 Parsing j7497.msgf.mzid.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Mon Aug 08 22:49:27 EDT 2016 Loading spectra for j7497.msgf.mzid.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Mon Aug 08 22:49:27 EDT 2016 Collecting peptides to map.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Mon Aug 08 22:49:28 EDT 2016 Mapping peptides to proteins.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Mon Aug 08 22:49:28 EDT 2016 Importing PSMs from j7497.msgf.mzid
10% 20% 30% 40% 50% 60%java.lang.StringIndexOutOfBoundsException: String index out of range: 24
    at java.lang.String.substring(String.java:1907)
    at com.compomics.util.experiment.biology.Protein.isNTerm(Protein.java:257)
    at com.compomics.util.experiment.biology.Peptide.isNterm(Peptide.java:639)
    at com.compomics.util.experiment.biology.Peptide.getPotentialModificationSites(Peptide.java:911)
    at com.compomics.util.experiment.biology.PTMFactory.getExpectedPTMs(PTMFactory.java:404)
    at eu.isas.peptideshaker.fileimport.PsmImporter.importAssumptions(PsmImporter.java:589)
    at eu.isas.peptideshaker.fileimport.PsmImporter.importPsm(PsmImporter.java:422)
    at eu.isas.peptideshaker.fileimport.PsmImporter.access$000(PsmImporter.java:68)
    at eu.isas.peptideshaker.fileimport.PsmImporter$PsmImporterRunnable.run(PsmImporter.java:1473)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

Mon Aug 08 22:49:32 EDT 2016 PeptideShaker Processing Canceled.
<CompomicsError>PeptideShaker processing canceled. See the PeptideShaker log for details.</CompomicsError>

```

**Comment by hbarsnes** [comment] 2016-08-11 08:46
Hi.

Thanks for telling us about this. The problem seems to be that your peptide sequence is longer than the protein sequence the peptide comes from. Not really sure how that can happen though... So would indeed be great if you could give us access to the data for further testing.

Best regards,
Harald

**Comment by hbarsnes** [comment] 2016-08-13 21:11
Hi again,

PeptideShaker v1.13.0 has just been released which hopefully fixes this issue. If this is not the case please let us know and we'll reopen the issue.

Best regards,
Harald

**Comment by videlc** [comment] 2017-01-05 23:11
Hey Harald,

Problem still seems to occur, at a way lower frequency with PeptideShaker-1.13.4 on CentOS (same machine as jflucier and max-l).
`
egrep "String index out of range" ./*/logs/*.log
./dir_shortened19/logs/PeptideShakerCLI_run.log:10% 20% 30% 40% 50% 60% 70% 80% 90%java.lang.StringIndexOutOfBoundsException: String index out of range: 24
./dir_shortened02/logs/PeptideShakerCLI_run.log:10% 20% 30% 40% 50% 60% 70% 80% 90%java.lang.StringIndexOutOfBoundsException: String index out of range: 16
./dir_shortened02/logs/PeptideShakerCLI_run.log:10% 20% 30% 40% 50%java.lang.StringIndexOutOfBoundsException: String index out of range: 28
./dir_shortened18/logs/PeptideShakerCLI_run.log:10% 20%java.lang.StringIndexOutOfBoundsException: String index out of range: 24
./dir_shortened18/logs/PeptideShakerCLI_run.log:10% 20% 30% 40% 50% 60% 70%java.lang.StringIndexOutOfBoundsException: String index out of range: 24
./dir_shortened02/logs/PeptideShakerCLI_run.log:10% 20%java.lang.StringIndexOutOfBoundsException: String index out of range: 28
./dir_shortened02/logs/PeptideShakerCLI_run.log:10% 20% 30% 40%java.lang.StringIndexOutOfBoundsException: String index out of range: 28
./dir_shortened10/logs/PeptideShakerCLI_run.log:10%java.lang.StringIndexOutOfBoundsException: String index out of range: 16
./dir_shortened10/logs/PeptideShakerCLI_run.log:10% 20%java.lang.StringIndexOutOfBoundsException: String index out of range: 24
./dir_shortened02/logs/PeptideShakerCLI_run.log:10% 20% 30% 40%java.lang.StringIndexOutOfBoundsException: String index out of range: 28
./dir_shortened19/logs/PeptideShakerCLI_run.log:10%java.lang.StringIndexOutOfBoundsException: String index out of range: 24
./dir_shortened18/logs/PeptideShakerCLI_run.log:10%java.lang.StringIndexOutOfBoundsException: String index out of range: 24
./dir_shortened02/logs/PeptideShakerCLI_run.log:10%java.lang.StringIndexOutOfBoundsException: String index out of range: 28
./dir_shortened17/logs/PeptideShakerCLI_run.log:10% 20% 30%java.lang.StringIndexOutOfBoundsException: String index out of range: 25
./dir_shortened18/logs/PeptideShakerCLI_run.log:10% 20% 30% 40% 50% 60% 70%java.lang.StringIndexOutOfBoundsException: String index out of range: 24
./dir_shortened19/logs/PeptideShakerCLI_run.log:10%java.lang.StringIndexOutOfBoundsException: String index out of range: 16
./dir_shortened19/logs/PeptideShakerCLI_run.log:10% 20%java.lang.StringIndexOutOfBoundsException: String index out of range: 16
`

To check if this issue was solved, I tried to perform one file manually on windows with the gui getting this with more details : 

`
```
Wed Jan 04 13:29:24 EST 2017        Importing sequences from searchgui_db_concatenated_target_decoy.fasta.
Wed Jan 04 13:31:03 EST 2017        FASTA file import completed.
Wed Jan 04 13:31:03 EST 2017        Importing gene mappings.
Wed Jan 04 13:31:11 EST 2017        Establishing local database connection.
Wed Jan 04 13:31:18 EST 2017        Reading identification files.
Wed Jan 04 13:31:18 EST 2017        Parsing dir_shortened_f19.comet.pep.xml.
Wed Jan 04 13:31:21 EST 2017        Loading spectra for dir_shortened_f19.comet.pep.xml.
Wed Jan 04 13:31:21 EST 2017        Importing dir_shortened_f19.mgf
Wed Jan 04 13:31:21 EST 2017        dir_shortened_f19.mgf imported.
Wed Jan 04 13:31:22 EST 2017        Collecting peptides to map.
Wed Jan 04 13:31:22 EST 2017        Mapping peptides to proteins.
Wed Jan 04 13:31:23 EST 2017        Importing PSMs from dir_shortened_f19.comet.pep.xml
Wed Jan 04 13:31:24 EST 2017        1479 identified spectra (4.3%) did not present a valid peptide.
Wed Jan 04 13:31:24 EST 2017        104360 of the best scoring peptides were excluded by the import filters:
Wed Jan 04 13:31:24 EST 2017            - 74.3% peptide length less than 8 or greater than 30.
Wed Jan 04 13:31:24 EST 2017            - 21.6% peptide presenting high mass or isotopic deviation.
Wed Jan 04 13:31:24 EST 2017            - 4.0% unrecognized modifications.
Wed Jan 04 13:31:24 EST 2017        Parsing dir_shortened_f19.msgf.mzid.
Wed Jan 04 13:31:32 EST 2017        Loading spectra for dir_shortened_f19.msgf.mzid.
Wed Jan 04 13:31:32 EST 2017        Collecting peptides to map.
Wed Jan 04 13:31:32 EST 2017        Mapping peptides to proteins.
Wed Jan 04 13:31:32 EST 2017        Importing PSMs from dir_shortened_f19.msgf.mzid
Wed Jan 04 13:31:33 EST 2017        286 identified spectra (0.9%) did not present a valid peptide.
Wed Jan 04 13:31:33 EST 2017        286 of the best scoring peptides were excluded by the import filters:
Wed Jan 04 13:31:33 EST 2017            - 85.3% peptide mapping to both target and decoy.
Wed Jan 04 13:31:33 EST 2017            - 14.7% peptide presenting high mass or isotopic deviation.
Wed Jan 04 13:31:33 EST 2017        Parsing dir_shortened_f19.t.xml.
Wed Jan 04 13:31:50 EST 2017        Loading spectra for dir_shortened_f19.t.xml.
Wed Jan 04 13:31:50 EST 2017        Collecting peptides to map.
Wed Jan 04 13:31:51 EST 2017        Mapping peptides to proteins.
Wed Jan 04 13:31:51 EST 2017        Importing PSMs from dir_shortened_f19.t.xml
Wed Jan 04 13:31:51 EST 2017        An error occurred: String index out of range: 24
Wed Jan 04 13:31:51 EST 2017        Please contact the developers (https://github.com/compomics/peptide-shaker/issues).

Wed Jan 04 13:31:51 EST 2017        Importing Data Canceled!
```
`

If you need files for example, let me know.

Best regards,
Vivian

**Comment by hbarsnes** [comment] 2017-01-06 10:56
Hi Vivian,

Thanks for the update. I will reopen the issue. Could you send me the data you are tying to load in PeptideShaker? In particular dir_shortened_f19.t.xml and the corresponding files (mgf, FASTA and search settings)? We will then try to reproduce the issue on our side and hopefully locate the problem.

Best regards,
Harald

**Comment by videlc** [comment] 2017-01-06 14:32
Hey Harald,

Files have been compressed and link sent to you via email.

Best,
Vivian

**Comment by hbarsnes** [comment] 2017-01-06 18:31
Hi Vivian,

Thanks for the files. I can confirm that I get the same issue on my side. I will try to locate the problem and get back to you as soon as possible.

Best regards,
Harald

**Comment by hbarsnes** [comment] 2017-01-06 23:54
Hi Vivian,

The problem is that your FASTA file contains multiple non-unique accession numbers.

For example:

```
>PK2L2
MAEASRWHRGVTFGMVNPHMYYLNKVMSSLFLDTSVPGEERTNFKSIRSITDFWKFMEGPLLEGLYWDSWYNNQQLYNLKNSSRIYYENILLGVPRVRQLKVRNNTCKVYSSFQSLMSECYGKYTSANEDLSNFGLQINTEWRYSTSNTNSPWHWGFLGVYRNGGYIFTLSKSKSETKNKFIDLRLNSWITRGTRVIFIDFSLYNANVNLFCIIRLVAEFPATGGILTSWQFYSVKLLRYVSYYDYFIASCEITFCIFLFVFTTQEVKKIKEFKSAYFKSIWNWLELLLLLLCFVAVSFNTYYNVQIFLLLGQLLKSTEKYSDFYFLACWHIYYNNIIAITIFFAWIKIFKFISFNKTMSQLSSTLSRCVKDIVGFAIMFFIIFFAYAQLGFLVFGSQVDDFSTFQNSIFAQFRIVLGDFNFAGIQQANPILGPIYFITFIFFVFFVLLNMFLAIINDTYSEVKADYSIGRRLDFELGKMIKQSYKNVLEKFRLKKAQKDEDKKTKGSGDLAEQARREGFDENEIQNAEQMKKWKERLEKKYYSMEIQDDYQPVTQEEFRELFLYAVELEKELHYINLKLNQVVRKVSAL
```

and 

```
>PK2L2
MAEASRWHRGGYVISIFGHFCAW
```

The accession number for both of these sequences will be PK2L2, which makes it impossible for PeptideShaker to know which protein sequence that is referenced to when the given accession number is used. In the case above, using the shorter protein sequence when actually referring to peptides from the longer protein sequence can result in the peptide sequence being longer than the protein sequence, and thus the processing breaking down.

In previous versions of our code we used to check for non-unique accession numbers when indexing the FASTA file, but for some reason we don't do this in the recent version. We will however re-add it in the next releases of both SearchGUI and PeptideShaker. 

Until this check has been re-added I would recommend that you check your FASTA file in a older version of PeptideShaker (for example [v1.9.0](http://genesis.ugent.be/maven2/eu/isas/peptideshaker/PeptideShaker/1.9.0/PeptideShaker-1.9.0.zip)). Simply reselect the FASTA file in the search settings dialog and correct the reported non-unique accession numbers. (You will have to do them one by one though, as the indexing stops at the first error each time. So you might have faster ways of fixing your FASTA file?)

When the FASTA file has been corrected you should be able to load your data in PeptideShaker. However, I would recommend also redoing the search, as the search engines may also have been confused by the non-unique accession numbers.

Finally, as this is an error in the FASTA file input and not in the PeptideShaker processing, I will now again close the issue. But please don't hesitate to open new issues if you come across other problems.

Best regards,
Harald

**Closed by hbarsnes** 2017-01-06 23:54 UTC
Labels: bug

**Comment by videlc** [comment] 2017-01-07 15:33
Hi Harald,

Thanks for fast troubleshooting.
Indeed, there were (a lot) duplicate accessions in our FASTA. A quick test indicated me there were thousands, so not possible to do manually.

I'll explain how i fixed it sothat if someone is having the same issue, this could help.

First, I converted FASTA to a TSV (TAB separated) with an R script found [here](https://www.researchgate.net/post/Converting_a_fasta_file_to_a_tab-delimited_file10)

Then, in R : 
```
> source('fasta2csv.R')
> tab<-read.table('output.tsv',sep='\t',header=FALSE)
> tab$V1<-make.unique(as.character(tab$V1),sep='-')
> write.table(tab,"tab.tsv",sep='\t',quote=FALSE,row.names=FALSE)
```

Then get back to FASTA format : 
 `sed -e s/\\\t/\\\n/g tab.tsv > fasta_no_duplicate.fasta`

Re-import in searchCLI to get DECOYs

**Then don't forget to remove two first lines which are variable names from R table (V1 and V2).**

Thanks again Harald !
Best regards, 
Vivian
