### ISSUE TITLE
Peptide Shaker 1.16.15 will not load searchGUI XTandem spectrum matches from .xml files

### ISSUE THREAD

**Issue by rocket0118** [compomics/peptide-shaker#298] opened 2018-01-29 23:03 UTC
Hi- 
  I'm testing Peptide Shaker 1.16.15 with XTandem on 19 Orbitrap .raw files from a 2D lc/ms/ms run, run on a windows 7 box (offline) with 24GB RAM. SearchGUI 3.2.20 processes the data (msconvert) without errors, an XTandem search finishes without errors, and seems to give reasonable results when looking at the .t.xml files opened with Excel. However when Peptide Shaker tries to import the SearchGUI-zipped xml files, I get the error (for each of 19 xml files)

Mon Jan 29 08:18:49 MST 2018          Parsing 0mM.t.xml. |   |   |  
Mon Jan 29 08:18:55 MST 2018          An error occurred while loading spectrum matches from '0mM.t.xml'.   This file will be ignored. Error: java.lang.NullPointerException See resources/PeptideShaker.log  for details. |   |   |  

log entries around this error:

Memory given to the Java virtual machine: 3817865216.
Total amount of memory in the Java virtual machine: 163053568.
Free memory: 146320664.
Java version: 1.8.0_144.
java.lang.ArrayIndexOutOfBoundsException: 21506	at com.compomics.util.experiment.identification.protein_inference.fm_index.Rank.getRank(Rank.java:115) 	at com.compomics.util.experiment.identification.protein_inference.fm_index.WaveletTree.getRankRecursive(WaveletTree.java:356)
	at com.compomics.util.experiment.identification.protein_inference.fm_index.WaveletTree.getRankRecursive(WaveletTree.java:359)
	at com.compomics.util.experiment.identification.protein_inference.fm_index.WaveletTree.getRankRecursive(WaveletTree.java:359)
	at com.compomics.util.experiment.identification.protein_inference.fm_index.WaveletTree.getRankRecursive(WaveletTree.java:359)
	at com.compomics.util.experiment.identification.protein_inference.fm_index.WaveletTree.getRankRecursive(WaveletTree.java:359)
	at com.compomics.util.experiment.identification.protein_inference.fm_index.WaveletTree.getRank(WaveletTree.java:338)
	at com.compomics.util.experiment.identification.protein_inference.fm_index.WaveletTree.prepareWaveletTree(WaveletTree.java:196)
	at com.compomics.util.experiment.identification.protein_inference.fm_index.WaveletTree.<init>(WaveletTree.java:140)
	at com.compomics.util.experiment.identification.protein_inference.fm_index.FMIndex.addDataToIndex(FMIndex.java:1115)
	at com.compomics.util.experiment.identification.protein_inference.fm_index.FMIndex.init(FMIndex.java:994)
	at com.compomics.util.experiment.identification.protein_inference.fm_index.FMIndex.<init>(FMIndex.java:486)
	at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getDefaultPeptideMapper(SequenceFactory.java:1449)
etc. 

 I noticed in other issues that using multiple variable modifications may be an issue (used 4 for initial test, can re-try with only 2). I can send the log file if this would be helpful- compomics would not accept it as a drag-and-drop attachment.

Thanks,
D Anderson

**Comment by hbarsnes** [comment] 2018-01-30 10:57
Hi D Anderson,

There seems to be a problem with the parsing of your FASTA file. Would you be able to share this file with us? Hopefully this will enable us to figure out what the problem is.

Best regards,
Harald

**Comment by rocket0118** [comment] 2018-01-30 23:24
Hi Harald-

Thanks for the email reply! I'd be happy to share it, what is the best
way to do this? It is over 30MB (~48000 sequences, of rhesus macaque,
Plasmodium vivax, and human/sheep cytokeratin contaminants, and a few
proteases), and includes reversed sequences (starting with XXX_ in the
fasta file, from prior use of MSGF+). I had to process it to remove
dots (stop codons in ~20 macaque protein sequences) and some keratins
that were giving errors, so I'm (unfortunately) not surprised. It
could be that the XXX_ entries are causing problems as well.
  Any advice on how better to construct it would be appreciated!

Thanks,
Dave Anderson

**Comment by hbarsnes** [comment] 2018-01-31 09:36
Hi Dave,

The reverse sequences should be added by SearchGUI when selecting the FASTA file. This also ensures that PeptideShaker is able to detect the reversed sequences correctly as the decoys, which is needed in the FDR caclulations.

So perhaps you could try removing the reversed sequences and let SearchGUI re-add them for you? I'd also recommend having a look at our database help page in case you have custom FASTA headers: http://compomics.github.io/projects/searchgui/wiki/databasehelp.html.

And regarding how to share the FASTA file, first zip it and then try to send it to me directly at harald.barsnes AT gmail.com. If this does not work (i.e. if the file is still too big), I'd recommend Dropbox or similar and then send me just the link.

Best regards,
Harald

**Comment by rocket0118** [comment] 2018-01-31 22:29
Hi Harald-

Thanks for the email reply and suggestions about the database! I'm
testing various subsections of the database to pinpoint what might be
causing the problems, and think you might be correct about the
reversed sequences being one concern. I had some non-standard sequence
headers of contaminant proteins, but can run SearchGUI and Peptide
Shaker when they are included. I'll try letting SearchGUI make the
reversed sequences to see if this fixes the problem(s).

Thanks,
Dave

**Comment by rocket0118** [comment] 2018-02-02 00:18
Hi Harald-

Thanks for the email reply! The "decoy" button in SearchGUI 3.2.20 is
grayed-out (and non-responsive) after I load a forward database (no
reversed sequences) for some reason, thus I can't add decoy sequences.
It is not grayed-out before a .fasta database is loaded.
 I'll send the database to your email address in two ~7 MB pieces,
each of which is zipped, if I can't send the 15MB zipped full
database.

Thanks,
Dave

**Comment by hbarsnes** [comment] 2018-02-02 14:14
Hi Dave,

It seems like several of your sequences are picked up as decoy headers. This is usually due to custom headers were we cannot figure out how to properly parse the headers to get the accession number. 

Please have a look at how to set up custom header to ensure that they are parsed properly by our tools: http://compomics.github.io/projects/searchgui/wiki/databasehelp.html#non-standard-fasta. Usually only requires a bit of search and replace to make the files compatible.

Best regards,
Harald

**Comment by rocket0118** [comment] 2018-02-02 23:32
Hi Harald-

  Thanks for the email reply! Might you have any idea why the "decoy"
button in SearchGUI is grayed-out when I load a fasta file before
creating reversed sequences? Perhaps reinstalling SeachGUI might help?

Thanks,
Dave

**Comment by hbarsnes** [comment] 2018-02-06 11:59
Hi Dave,

Reinstalling SearchGUI will not have any effect on the issue. It can only be solved by reformatting your FASTA file according to the information found here: http://compomics.github.io/projects/searchgui/wiki/databasehelp.html#non-standard-fasta.

Best regards,
Harald

**Comment by rocket0118** [comment] 2018-02-06 23:46
Hi Harald-

Reformatting the database worked!

Thanks,
Dave Anderson

**Comment by hbarsnes** [comment] 2018-02-07 12:27
Hi Dave,

Great! I will then close the issue. But don't hesitate to open a new one if you come across other problems.

Best regards,
Harald

**Closed by hbarsnes** 2018-02-07 12:27 UTC
Labels: bug
