### ISSUE TITLE
Missing Spectrum files when using ReportCLI and MzidCLI

### ISSUE THREAD

**Issue by nelson42** [compomics/peptide-shaker#386] opened 2020-01-02 16:34 UTC
Hi,

I'm encountering an error when attempting to export Reports and Mzids. PeptideShaker appears to load in the cpsx and then exits with the following error message:

`10% 30% 40% 50% 90%
Thu Jan 02 16:14:32 GMT 2020 The spectrum file was not found. Please provide its location in the command line parameters.`

From what I can see in the CLI readme these two functions shouldn't need the spectrum files. If I try to provide them using -spectrum_files PeptideShaker exits with the following different error so I don't think that is the right approach either.

`<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>`

The cpsx file was created with the following commands, maybe I am doing something wrong upstream that is causing the issues?
   
    java -d64 -Xms500G -Xmx501G -cp /mnt/fls01-home01/mfbx6mn3/scratch/paper/35fraction/PeptideShaker-1.16.42/PeptideShaker-1.16.42.jar  eu.isas.peptideshaker.cmd.PathSettingsCLI -temp_folder "/mnt/fls01-home01/mfbx6mn3/scratch/paper/35fraction/temp/"
    
    java -d64 -Xms500G -Xmx501G -cp /mnt/fls01-home01/mfbx6mn3/scratch/paper/35fraction/PeptideShaker-1.16.42/PeptideShaker-1.16.42.jar  eu.isas.peptideshaker.cmd.PeptideShakerCLI -experiment rep1 -sample rep1_sample -replicate 1 -identification_files "/mnt/fls01-home01/mfbx6mn3/scratch/paper/35fraction/searchgui_out.zip"  -out "/mnt/fls01-home01/mfbx6mn3/scratch/paper/35fraction/35fraction.cpsx"  
    
    java -d64 -Xms500G -Xmx501G -cp /mnt/fls01-home01/mfbx6mn3/scratch/paper/35fraction/PeptideShaker-1.16.42/PeptideShaker-1.16.42.jar  eu.isas.peptideshaker.cmd.ReportCLI -in "/mnt/fls01-home01/mfbx6mn3/scratch/paper/35fraction/35fraction.cpsx" -out_reports "/mnt/fls01-home01/mfbx6mn3/scratch/paper/35fraction/" -reports "6" 

Thanks very much,

Mike

**Comment by hbarsnes** [comment] 2020-01-06 12:45
Hi Mike,

I think the problem is that the spectrum files are inside the searchgui_out.zip file and therefore not available when running the ReportCLI command line.

The easiest solution is to merge the PeptideShakerCLI and ReportCLI command lines. This should also be faster as you then do not have to save and reopen the cpsx file before creating the reports.

So try adding `-out_reports "/mnt/fls01-home01/mfbx6mn3/scratch/paper/35fraction/" -reports "6"` to the end of your PeptideShakerCLI command line to see it that solves the problem?

You can use the same trick for the MzidCLI export options as well.

Best regards,
Harald

**Comment by nelson42** [comment] 2020-01-07 17:00
Hi Harald, 

Thanks very much for the reply, I'm giving that a go now. I think this is something that I did have set up on a previous version so I'm sure it will work.

Thanks for the help, 

Mike

**Comment by hbarsnes** [comment] 2020-01-08 13:01
Hi Mike,

Great! I will then close the issue, but please let us know if you still experience issues and we'll reopen the issue.

Best regards,
Harald

**Closed by hbarsnes** 2020-01-08 13:01 UTC
Labels: help wanted
