### ISSUE TITLE
PeptideShaker hangs during opening on 64-bit Windows systems

### ISSUE THREAD

**Issue by AnotherKiwi** [compomics/peptide-shaker#171] opened 2016-05-16 23:39 UTC
I'm having trouble gettng PeptideShaker to run on my work Windows 7 Enterprise system and on my Windows 10 home PC. On first run it successfully creates the desktop icon but then hangs. Subsequently, it hangs at the splash screen when trying to open PeptideShaker (e.g. using the created icon).

Both systems have 64-bit Java installed. Here's the contents of startup.log after I kill the splash screen process on my work PC:

Memory settings read from the user preferences: 8096
args: 
original java.home: C:\Program Files\Java\jre1.8.0_77\bin\
new java.home: C:\Program Files\Java\jre1.8.0_77\bin\
New memory setting saved: 8096

Command line: 
"C:\Program Files\Java\jre1.8.0_77\bin\java" -splash:resources\conf\peptide-shaker-splash.png -Xms128M  -Dhttp.proxyHost=webgate.agresearch.co.nz -Dhttp.proxyPort=8080 -Dhttp.proxyUser=hainess -Dhttp.proxyPassword=*********** -Xmx8096M -cp "C:\Users\hainess\Apps\PeptideShaker-1.10.3\PeptideShaker-1.10.3.jar" eu.isas.peptideshaker.gui.PeptideShakerGUI 
Process exitValue: 1

I've uploaded PeptideShaker.log, which shows a number NullPointerExceptions.

The problem happens with both PeptideShaker v 1.9.2 and 1.10.3.

Can you suggest what is preventing PeptideShaker from loading? Note that SearchGUI 2.8.6 opens without problems on both PC.

Thanks
Stephen

[PeptideShaker log.zip](https://github.com/compomics/peptide-shaker/files/267115/PeptideShaker.log.zip)

**Comment by AnotherKiwi** [comment] 2016-05-17 01:36
I've now tried running PeptideShaker 1.10.3 on a 32-bit Windows 7 PC, with version 8U91 of the JRE, and got the same result.

Stephen

**Comment by hbarsnes** [comment] 2016-05-19 12:14
Hi Stephen,

Thanks for telling us about this. Could you try the below beta version? It should fix the NullPointerExceptions in the log file, where it seems like that PeptideShaker is trying to resize itself before it's actually visible.

https://www.dropbox.com/s/1292s9q7llsudbj/PeptideShaker-1.10.4-beta.zip?dl=0

The fix could potentially just result in other errors instead, as I cannot reproduce the problem on my side. So please send me the updated log file if this happens.

And you could also try running PeptideShaker without the proxy settings?

Best regards,
Harald

**Comment by AnotherKiwi** [comment] 2016-05-19 18:13
Thanks Harald

I actually tried running PeptideShaker without the proxy settings before adding them to my configuration (in case being able to access the internet fixed the problem).

I've just tried the beta version on my Windows 10 home system and got the same result as before. On first start PeptideShaker showed that it couldn't access the path for its matches folder, so I changed it to one that it could and then it immediately hung with the error message shown in the attached screenshot. This time it didn't get to the point of creating the desktop icon.

I've attached the log.

That was actually the first sign of a problem on the two work PCs that I tried running PeptideShaker 1.10.3 on. With those, though, after giving the error message following the change of matches folder PeptideShaker got as far as creating the desktop icon. Apologies for forgetting to mention that in my original post!

I will try the beta version on my work Windows 7 PC later this morning in case PeptideShaker likes the earlier version of Windows, and let you know how that goes.

Kind regards
Stephen

![peptideshaker_2016-05-20_05-47-19](https://cloud.githubusercontent.com/assets/17808219/15404188/6e50630a-1e50-11e6-9dca-7fd3308dfcd3.png)
[PeptideShaker log.zip](https://github.com/compomics/peptide-shaker/files/273160/PeptideShaker.log.zip)

**Comment by hbarsnes** [comment] 2016-05-19 20:19
Hi Stephen,

Thanks for the update. We've never had this issue on Windows 10 before, so I don't think that is the problem.

> I've just tried the beta version on my Windows 10 home system and got the same result as before. On first start PeptideShaker showed that it couldn't access the path for its matches folder, so I changed it to one that it could and then it immediately hung with the error message shown in the attached screenshot. This time it didn't get to the point of creating the desktop icon.

From your log file I see that you're unzipping PeptideShaker into "C:\Users\Haines\Apps\". I assume you (and as a consequence PeptideShaker) have writing access to this folder? If so, there should be no need to change the matches folder? As the default matches folder is just "C:\Users\Haines\Apps\PeptideShaker-1.10.4-beta\PeptideShaker-1.10.4-beta\resources\matches" in your case. Do you see any obvious reason why you cannot access this folder?

Could you try simply unzipping the PeptideShaker zip file on your desktop and double click the PeptideShaker jar file?

Best regards,
Harald

**Comment by hbarsnes** [comment] 2016-05-19 20:45
Hi again,

Here's another beta version (note: same version number as the previous beta version) that ought to fix the first NullPointerException in your log file. The one that occurs when restarting PeptideShaker with a new matches folder.

https://www.dropbox.com/s/kd4qeo7i96j7a2w/PeptideShaker-1.10.4-beta-v2.zip?dl=0

Still don't understand why you cannot access the matches folder in the first place though..?

Best regards,
Harald

**Comment by AnotherKiwi** [comment] 2016-05-19 20:55
Hi Harald

I have full privileges to C:\Users\Haines\Apps.

The default matches folder starts as C:\Program Files\FreeCommanderXE\resources (see first screenshot), no doubt because after unzipping PeptideShaker I'm opening it from FreeCommander.

I then changed the matches folder to C:\Users\Haines\.peptideshaker\matches, which PeptideShaker seems happy about (see second screenshot).

After clicking OK, PeptideShaker restarts and I get the error message.

Regards
Stephen

![java_2016-05-20_08-50-22](https://cloud.githubusercontent.com/assets/17808219/15409267/25e75fe8-1e68-11e6-8836-79fdb2828039.png)


![java_2016-05-20_08-43-36](https://cloud.githubusercontent.com/assets/17808219/15409078/5737d362-1e67-11e6-89ae-b5c75ec8c71a.png)

**Comment by AnotherKiwi** [comment] 2016-05-19 21:11
Hi Harald

I just tried unzipping the beta version 2 to my desktop, created a matches folder in the resources folder, and double clicked to start.

PeptideShaker then created an icon and hung, without any error message.

I've attached the log.

Regards
Stephen


[PeptideShaker log.zip](https://github.com/compomics/peptide-shaker/files/273475/PeptideShaker.log.zip)

**Comment by hbarsnes** [comment] 2016-05-19 21:14
Hi Stephen,

> The default matches folder starts as C:\Program Files\FreeCommanderXE\resources (see first screenshot), no doubt because after unzipping PeptideShaker I'm opening it from FreeCommander.

I'd recommend just right clicking the zip file and choose the "Extract All.." option (I'm on Windows 7, but I assume there is something similar on Windows 10?) instead of using a special setup such as FreeCommander. Especially if FreeCommander changes the unzipped folder structure and/or context.

Are you using FreeCommander on the other tested machines as well btw?

Best regards,
Harald

**Comment by AnotherKiwi** [comment] 2016-05-19 22:48
Hi Harald

FreeCommander is just a file manager equivalent of Windows Explorer. I simply use it to select the zip file to be extracted, and it has no effect on the folder structure or content. Running programs by double-clicking in FreeCommander is just the same as doing that in Windows Explorer.

Just to confirm this, I just redownloaded the beta version 2 directly to the desktop of my work Windows 7 PC, and used Extract All..., then double-clicked the PeptideShaker jar file in the Windows Explorer window that opened showing the extracted files. As on my home system, PeptideShaker hung after I told it to create a desktop icon.

I've attached the log, which seems to show PeptideShaker is creating incorrect filepaths (on this corporate networked system at least):
java.io.FileNotFoundException: \\LFS\hainess$\Desktop\PeptideShaker-1.10.4-beta-v2\PeptideShaker-1.10.4-beta\hainess$\Desktop\PeptideShaker-1.10.4-beta-v2\PeptideShaker-1.10.4-beta\PeptideShaker-1.10.4-beta.jar (The system cannot find the file specified)

It has repeated the '\hainess$\Desktop\PeptideShaker-1.10.4-beta-v2\PeptideShaker-1.10.4-beta\' part of the path. I didn't look at the log on my home system to know if it did the same on that PC.

Regards
Stephen

[PeptideShaker log.zip](https://github.com/compomics/peptide-shaker/files/273601/PeptideShaker.log.zip)

**Comment by hbarsnes** [comment] 2016-05-20 11:49
Hi Stephen,

> FreeCommander is just a file manager equivalent of Windows Explorer. I simply use it to select the zip file to be extracted, and it has no effect on the folder structure or content. Running programs by double-clicking in FreeCommander is just the same as doing that in Windows Explorer.

I would argue that this does not seem to be the case for PeptideShaker? Not sure why though. Or via it works for SearchGUI and not for PeptideShaker.

> It has repeated the '\hainess$\Desktop\PeptideShaker-1.10.4-beta-v2\PeptideShaker-1.10.4-beta\' part of the path.

If this is a Windows system via is does it start with "\" and why is there a "$" in there? Is this again due to FreeCommander? Are you putting PeptideShaker in a path with some sort of symbolic linking?

Best regards,
Harald

**Comment by AnotherKiwi** [comment] 2016-05-20 19:33
Hi Harald

 

                I would argue that this does not seem to be the case for PeptideShaker?

 

I suspect the only influence FreeCommander has had on the situation is that on first run of PeptideShaker from it, the FreeCommander program folder (“C:\Program Files\FreeCommanderXE”) was the current folder in the process from which PeptideShaker was launched. PeptideShaker has appended “resources” to that to generate its matches path. Why it should do that for the matches path alone, rather than use the root user folder (C:\Users\Haines on my home PC) as it did for all its other resource folders, I don’t know.

 

So use of FreeCommander caused the resource folders dialog to appear simply because PeptideShaker couldn’t access the generated matches path in the Program Files folder structure. However once I had supplied a path to which PeptideShaker did have privileges to access, it got past that point and I suspect FreeCommander had no further influence on the running of PeptideShaker.

 

Since my use of FreeCommander has obviously complicated and confused the situation (apologies for that), in my most recent tests with the version 2 beta on both my Windows 10 home system and my Windows 7 work PC I have avoided its use. Instead I directly extracted the ZIP file on my desktop and ran PeptideShaker by right clicking, choosing “Extract All…”, then double clicked the JAR file from Windows Explorer. On both PCs, PeptideShaker hung after offering to create a desktop icon.

 

If this is a Windows system …. why is there a "$" in there? Is this again due to FreeCommander? Are you putting PeptideShaker in a path with some sort of symbolic linking?

 

The “$” appeared in the log file from my work PC is because that PC is on a corporate Windows network, and yes there is symbolic linking involved. The network maps the standard user root folder (C:\User\<username>) to a private folder on a network drive (hence the “$”, which Windows uses to indicate a non-shared folder). In my case my work username is “hainess” and the network drive my profile resides on is \\LFS <file:///\\LFS> , so the network maps “C:\User\hainess” to “\\LFS\hainess$”. All my standard Windows folders (My Documents, My Pictures etc) are sub-folders of the “hainess$” folder on “LFS”. Hence when PeptideShaker acquires the path to “My Documents” from Windows, it will receive the path with the “$” in it.

 

                If this is a Windows system via is does it start with "\" 

 

The error message on my work PC suggests that PeptideShaker is not correctly parsing the “\\LFS” of my mapped user directory, hence the “\” at the start of the path reported in the java error message (“java.io.FileNotFoundException: \LFS\hainess$\Desktop\PeptideS…”)

 

So, perhaps different issues causing PeptideShaker to fail on my work PC and on my home PC?

 

Kind regards

Stephen

**Comment by hbarsnes** [comment] 2016-05-20 19:58
Hi Stephen,

> So, perhaps different issues causing PeptideShaker to fail on my work PC and on my home PC?

Yes, I guess that could be the case. Strange that you get similar errors that we have not seen before on multiple setups though?

> The error message on my work PC suggests that PeptideShaker is not correctly parsing the “\\LFS” of my mapped user directory, hence the “\” at the start of the path reported in the java error message (“java.io.FileNotFoundException: \LFS\hainess$\Desktop\PeptideS…”)

The thing is that we are not actually parsing this path ourselves (or at least not processing it). We are simply trying to extract the path via standard Java code to get PeptideShaker to tell us where it is installed. So it is rather limited in terms of what we can change here I'm afraid.

The issues seem to be related to one of two things: the adding of the shortcut and the check for new versions. Perhaps you can try to say 'no' to the adding of the shortcut to see if that helps? Also, try starting PeptideShaker without an internet connection as this should disable the check for new versions. (You can disable the check from inside the user interface later if this works.)

We use exactly the same code in SearchGUI though, so did you do anything differently with SearchGUI compared to PeptideShaker?

Finally, perhaps you could try running PeptideShaker from the command line and thus manually correct some of the path issues that way?

The command line should be something like:
java -Xmx8096M -cp C:\Users\hainess\Apps\PeptideShaker-1.10.3\PeptideShaker-1.10.3.jar eu.isas.peptideshaker.gui.PeptideShakerGUI 

You can add the proxy settings and create a proper shortcut later.

Best regards,
Harald

**Comment by AnotherKiwi** [comment] 2016-05-20 22:19
Hi Harald

> We use exactly the same code in SearchGUI though, so did you do anything differently with SearchGUI compared to PeptideShaker?

No, nothing at all. SearchGUI works well on both my work PC and my home system. Strange!

> Perhaps you can try to say 'no' to the adding of the shortcut to see if that helps? Also, try starting PeptideShaker without an internet connection as this should disable the check for new versions. 

I'm at home so can only test this on my Windows 10 PC. Saying 'no' to the shortcut creation and having the internet disconnected had no effect. Similarly running from the command line had no effect...the java process simply hung using no CPU time.

I've attached the log file resulting from these tests.

Kind regards
Stephen
[PeptideShaker log.zip](https://github.com/compomics/peptide-shaker/files/275515/PeptideShaker.log.zip)

**Comment by hbarsnes** [comment] 2016-05-20 23:20
Hi Stephen,

Maybe we've been looking at the wrong place. The problem might be the reading of the PeptideShaker (and SearchGUI) user preferences. At least that is one possible explanation for the null pointer exceptions.

Try removing your PeptideShaker (and SearchGUI) user preferences. The default folder for this is "user home"\.compomics\. Simply delete the two files userpreferences.cup and utilities_userpreferences.cup (you may only have one of them). They will be recreated the next time you start the tool. Also delete any custom path settings you may have by deleting the paths.txt file in the PeptideShaker-1.10.4-beta\resources\conf folder. Then restart PeptideShaker by double clicking the jar file.

If it still does not work, try out this new beta version. Will most likely just move the errors elsewhere in the code though...

https://www.dropbox.com/s/dnakrzlmgd1wxe6/PeptideShaker-1.10.4-beta-v3.zip?dl=0

Best regards,
Harald

**Comment by AnotherKiwi** [comment] 2016-05-21 00:06
Hi Harald

I removed my PeptideShaker (and SearchGUI) user preferences (I had both files), but I didn't have a paths.txt in the PeptideShaker conf folder. Once again java hung after starting PeptideShaker.

The new beta also hung. As you thought, it seems to have struck an error in a different place. The log file is attached.

Kind regards
Stephen

[PeptideShaker log.zip](https://github.com/compomics/peptide-shaker/files/275597/PeptideShaker.log.zip)

**Comment by hbarsnes** [comment] 2016-05-21 01:22
Hi Stephen,

Ok, so we still have errors related to the reading of the user preferences. The question is why. Here's yet another beta version, this time printing more debugging details regarding the user preferences files to the log file. Hopefully this can shed some light on what is going on.

https://www.dropbox.com/s/1cwtff78288dq8o/PeptideShaker-1.10.4-beta-v4.zip?dl=0

Best regards,
Harald

**Comment by AnotherKiwi** [comment] 2016-05-21 04:56
Hi Harald

The log does contain a couple of error messages, but this version opens successfully :)

It gives an error message about the 'HeLa Example.cpsx' not being created with a compatible version of PeptideShaker when I try to open the example project, but the user interface looks normal.

Looks like you are definitely on the right track!

Kind regards
Stephen

[PeptideShaker log.zip](https://github.com/compomics/peptide-shaker/files/275709/PeptideShaker.log.zip)

**Comment by hbarsnes** [comment] 2016-05-21 09:50
Hi Stephen,

I'm afraid there is no actual progress as it still struggles to open the user preferences. The problem seems to be the file "C:\Users\Haines\.peptideshaker\userpreferences.cpf", which it finds and tries to read, but then later in when it wants to use the content it is null. Makes very little sense to me as no errors are thrown to indicate any problems with the file.

Try deleting all the user preferences as above again, but this time also delete the ".peptideshaker\userpreferences.cpf" file. Perhaps the content got messed up in a previous version.

Best regards,
Harald

**Comment by AnotherKiwi** [comment] 2016-05-21 09:59
Hi Harald

That worked. PeptideShaker opened and was able to load the example project :+1: 

The userpreferences.cpf file was only 5 bytes, so presumably had been corrupted at some stage.

Kind regards
Stephen

**Comment by hbarsnes** [comment] 2016-05-21 10:10
Hi Stephen,

Great! So everything now finally works as it should on your home PC then? If so, please let me know later if the same trick also resolves the problem on your work PC?

Best regards,
Harald

**Comment by AnotherKiwi** [comment] 2016-05-21 21:32
Hi Harald

Will let you know tomorrow if that fixes the problem on my work computer. Many thanks for all your late night efforts helping with this issue!

In the meantime, I have a question about how to export the peptide table information from the overview tab for multiple proteins. Would you prefer I post that as a separate issue?

Kind regards
Stephen

**Comment by hbarsnes** [comment] 2016-05-21 23:38
Hi Stephen,

> I have a question about how to export the peptide table information from the overview tab for multiple proteins.

Use the Identification Features option in the Export menu at the top of the frame. Choose either the Default Peptide Report or make your own custom report with the information you need.

Best regards,
Harald

**Comment by AnotherKiwi** [comment] 2016-05-22 00:34
Hi Harald

Duh...good example of how it pays to read the documentation first! Thanks for that steer.

Kind regards
Stephen

**Comment by AnotherKiwi** [comment] 2016-05-22 17:49
Hi Harald

Although PeptideShaker now works with the example data on my home PC, when I run a SearchGUI search and try to open the results in PeptideShaker the latter operation fails.

Just to be sure I was starting with a "clean slate", I deleted all the user preference files from the .compomics and .peptideshaker folders, then opened PeptideShaker and confirmed I could load the example project. I then closed PeptideShaker. Next I opened SearchGUI and ran an X!Tandem search, after clicking the post processing option and supplying a project and sample name for PeptideShaker. The search completed successfully but an error occurred when PeptideShaker tried to open the results.

> Mon May 23 05:22:03 NZST 2016        Processing identification files with PeptideShaker.
> Mon May 23 05:22:04 NZST 2016        PeptideShaker processing failed. See the PeptideShaker log for details.
> Mon May 23 05:22:04 NZST 2016        Search Canceled!
> java.lang.NullPointerException

I've attached the PeptideShaker log and the SearchGUI log, report, and result file so that hopefully you will be able to see is preventing PeptideShaker from opening SearchGUI search results on my system.

Kind regards
Stephen

[PeptideShaker log.zip](https://github.com/compomics/peptide-shaker/files/276484/PeptideShaker.log.zip)
[SearchGUI log.zip](https://github.com/compomics/peptide-shaker/files/276487/SearchGUI.log.zip)
[SearchGUI report.txt](https://github.com/compomics/peptide-shaker/files/276488/SearchGUI.report.txt)
[searchgui_out.zip](https://github.com/compomics/peptide-shaker/files/276489/searchgui_out.zip)

**Comment by AnotherKiwi** [comment] 2016-05-22 17:54
Hi Harald

I just tried opening the search result by creating a new project in PeptideShaker, and that worked. So it's just the link between SearchGUI and PeptideShaker that isn't working.

Kind regards
Stephen

**Comment by AnotherKiwi** [comment] 2016-05-22 20:41
Hi Harald

Just tried running beta 4 on my work PC after deleting my user preference files, and it works on that system as well :)

Once again, many thanks for getting this issue sorted.

Kind regards
Stephen

**Comment by hbarsnes** [comment] 2016-05-22 22:35
Hi Stephen,

> I've attached the PeptideShaker log and the SearchGUI log, report, and result file so that hopefully you will be able to see is preventing PeptideShaker from opening SearchGUI search results on my system.

Thanks for telling us about this. There was a typo in the PeptideShaker command line where the id_params option was not preceded by a '-'. Has now been fixed and we'll release a new version as soon as possible.

Best regards,
Harald

**Comment by hbarsnes** [comment] 2016-06-07 20:44
Hi Stephen,

The link between SearchGUI and PeptideShaker should be fixed in the just released new versions. If this is not the case, please let us know and we'll reopen the issue.

Best regards,
Harald

**Closed by hbarsnes** 2016-06-07 20:44 UTC
Labels: help wanted

**Comment by AnotherKiwi** [comment] 2016-06-08 19:22
Thanks Harald

 

Kind regards

Stephen
