### ISSUE TITLE
Error when sorting spectrum IDs by Sequence

### ISSUE THREAD

**Issue by mesontau** [compomics/peptide-shaker#112] opened 2016-01-14 09:34 UTC
Hi,

I get an error in PeptideShaker 1.3.6 when I try to sort the spectrum IDs by Sequence that shows the following message:

"An error occurred: Index 21186, Size 21087."

When I press the OK button to continue, the error reproduces just adding +1 to the index. After pressing OK for some (many) times, it starts over again with the initial index. It then runs over the error cycle a total of two times, after which the spectrum ID list looks to be sorted. I can see also that the list contains multiple empty lines (see attached screenshot)

![screen shot 2016-01-14 at 09 48 54](https://cloud.githubusercontent.com/assets/10231211/12319836/3ed10364-baa5-11e5-9233-762500a19438.png)

(below these blank lines there are more lines containing data)

It is not a big deal, but just annoying since you need to press OK about 100 times.

**Comment by hbarsnes** [comment] 2016-01-14 09:53
Hi.

Thanks for telling us about this. Could you send us your PeptideShaker log file?  You'll find it via the Welcome dialog > Settings & Help > Help > Bug Report. This shoudl enable us to locate the problem, as I'm not able to reproduce the issue on my side.

Best regards,
Harald

**Comment by mesontau** [comment] 2016-01-14 10:05
Hi Harald,

sure! Thanks for taking care of this. I can also share with you the .cpsx project if you needed. 

Best regards,

Pedro.

[PeptideShaker 1.3.6 log.txt](https://github.com/compomics/peptide-shaker/files/90206/PeptideShaker.1.3.6.log.txt)

**Comment by hbarsnes** [comment] 2016-01-14 10:26
Hi Pedro,

Thanks for the log file. There seems to be an issue in the indexing of your mgf file I think, as it tries to display information for spectrum number 21091, 21186 or 21453, etc, when there are only 21087 spectra in the given mgf file.

Could you try deleting the mgf indexes (the files called .mgf.cui located in the same folder as the mgf files) and see if that helps? If it doesn't it would be great if you could zip the PeptideShaker project (via the Export > PeptideShaker Project As > Zip File) and make it available to us?

BTW, which search engines are the search results from, and was the search run in SearchGUI? If so, did you get any warnings when the mgf files were processed, like duplicated spectrum titles?

Best regards,
Harald

**Comment by mesontau** [comment] 2016-01-15 12:32
Hi Harald,

I removed the .cui files, and that helped! Thanks! I don't know why the bad indexing was produced, though. 

I searched the files with X!Tandem, MS-GF+, and Comet. Everything was performed in SearchGUI + PeptideShaker, including file conversion from raw format (Waters raw files). I didn't get any warning during the search (see attached SearchGUI report) as far as I can see. 

Thanks again for your help!

Best regards,
Pedro.

[SearchGUI Report 2016-01-13 18.58.43.html.zip](https://github.com/compomics/peptide-shaker/files/91831/SearchGUI.Report.2016-01-13.18.58.43.html.zip)

**Comment by hbarsnes** [comment] 2016-01-15 13:32
Hi Pedro,

Good to hear that the issue was resolved. I'm also unsure how/why the mgf indexes got corrupted. In most cases we should simply regenerate the index, e.g. if the mgf file has changed. And we've never seen this issue before. Which I guess we should if this could occur often.

And I don't see any errors in the SearchGUI log file either. I do note that your files are stored on X:\ though, which usually indicates an external drive. Is this the case? If so, this could perhaps somehow explain the changed index, but not really sure how. In any case it is generally recommended to keep all the files on the same machine as the one running SearchGUI and PeptideShaker, as this will reduce the chance of these types of issues occurring, and equally important it is usually a lot quicker.

Anyway, given that remaking the indexes solved the problem I will now close this issue. But if it happens again please let us know and we'll reopen it.

Best regards,
Harald

**Closed by hbarsnes** 2016-01-15 13:32 UTC
Labels: bug
