### ISSUE TITLE
Fatal error: Tide could not read index

### ISSUE THREAD

**Issue by krawson14** [compomics/peptide-shaker#201] opened 2016-08-29 22:17 UTC
In running SearchGUI 3.1.0 through with Tide as one of the selected algorithms, I receive a fatal error stating:

FATAL: Error reading index (fasta-index\pepix)

An additional part of the error returned is:

Mon Aug 29 22:11:03 UTC 2016        Error: Source 'D:\Software\SearchGUI-3.1.0\resources\Tide\windows\windows_64bit\crux-output\*********23Aug2016_1_50_fix.tide-search.target.txt' does not exist

I am supplying the algorithm with .mgf files that were obtained from conversion of the RAW file with MSConvert using centroid mode. All other algorithms that I have tried running (X!Tandem, Comet, OMSSA, MS-GF+) have all successfully completed for this file. Running on Windows Server 2012 64-bit.

**Comment by hbarsnes** [comment] 2016-08-30 10:00
Hi,

For issues with the search engines themselves I would recommend that you contact the search engine developers directly, as there is not much we can do unless the problem is our input to the search engine. 

For Tide there is a Google Group where you can ask questions: https://groups.google.com/forum/#!forum/crux-users. Hopefully they will be able to help you. BTW, I'm on that list too, so if the result is that we need to change something in SearchGUI I'll know about it.

Also, if you don't specifically have to run Tide you could leave it out and run SearchGUI with the other search engines instead. Comet and Tide are basically the same algorithm anyway (both based on Sequest), so if you include Comet you should get more or less the same results as with Tide.

I will now close the issue and move further followup to the above Google Group.

Best regards.
Harald

**Closed by hbarsnes** 2016-08-30 10:00 UTC
Labels: help wanted
