### ISSUE TITLE
Open reports with PeptideShaker - null error

### ISSUE THREAD

**Issue by StullenBrot** [compomics/peptide-shaker#219] opened 2016-11-03 13:19 UTC
Hello,

I recently wanted to start using SearchGUI and Peptideshaker for Protein evaluation and made my first steps using X!Tandem and Amandy search engines on a few of my data files. After the search I wanted to open the result with PeptideShaker 1.13.6 and got a null error.  
The Report I got is here:

> Thu Nov 03 09:25:36 CET 2016        Import process for Test (Sample: directOx, Replicate: 0)
> 
> Thu Nov 03 09:25:36 CET 2016        Importing sequences from uniprot_Human_reviewed_concatenated_target_decoy.fasta.
> Thu Nov 03 09:25:59 CET 2016        FASTA file import completed.
> Thu Nov 03 09:25:59 CET 2016        Importing gene mappings.
> Thu Nov 03 09:26:00 CET 2016            Neanderthal (Homo sapiens neanderthalensis) not available in Ensembl. Gene and GO annotation for this species will not be available.
> Thu Nov 03 09:26:01 CET 2016        Establishing local database connection.
> Thu Nov 03 09:26:03 CET 2016        Reading identification files.
> Thu Nov 03 09:26:03 CET 2016        Parsing SF21_CIDexcl_C1.ms-amanda.csv.
> Thu Nov 03 09:26:04 CET 2016        Loading spectra for SF21_CIDexcl_C1.ms-amanda.csv.
> Thu Nov 03 09:26:04 CET 2016        Importing SF21_CIDexcl_C1.mgf
> Thu Nov 03 09:26:04 CET 2016        SF21_CIDexcl_C1.mgf imported.
> Thu Nov 03 09:26:04 CET 2016        Importing PSMs from SF21_CIDexcl_C1.ms-amanda.csv
> Thu Nov 03 09:26:06 CET 2016        PeptideShaker is encountering memory issues! See http://compomics.github.io/projects/peptide-shaker.html for help.
> Thu Nov 03 09:26:06 CET 2016        Reducing Memory Consumption.
> Thu Nov 03 09:26:09 CET 2016        1 identified spectra (0.0%) did not present a valid peptide.
> Thu Nov 03 09:26:09 CET 2016        1174 of the best scoring peptides were excluded by the import filters:
> Thu Nov 03 09:26:09 CET 2016            - 1.4% peptide mapping to both target and decoy.
> Thu Nov 03 09:26:09 CET 2016            - 95.8% peptide length less than 6 or greater than 30.
> Thu Nov 03 09:26:09 CET 2016            - 2.8% peptide presenting high mass or isotopic deviation.
> Thu Nov 03 09:26:09 CET 2016        Parsing SF21_CIDexcl_C1.t.xml.
> Thu Nov 03 09:26:11 CET 2016        Loading spectra for SF21_CIDexcl_C1.t.xml.
> Thu Nov 03 09:26:11 CET 2016        Importing PSMs from SF21_CIDexcl_C1.t.xml
> Thu Nov 03 09:26:11 CET 2016        An error occurred: null
> Thu Nov 03 09:26:11 CET 2016        Please contact the developers (https://github.com/compomics/peptide-shaker/issues).
> 
> Thu Nov 03 09:26:11 CET 2016        Importing Data Canceled!

Hope you can help me to solve the problem. 
Thank you very much.

Dennis

**Comment by hbarsnes** [comment] 2016-11-03 16:15
Hi Dennis,

Thanks for telling us about this. There seems to be a problem with the loading of your X! Tandem results. Could you share with us the PeptideShaker log file? You'll find it via the PeptideShaker Welcome dialog > Settings & Help > Help > Bug Report. The content of the log file will tell us a bit more about what the problem is.

If I could also add two pieces of advice. First, check the content of your FASTA file as it seems to contain sequences from Neanderthal ("Neanderthal (Homo sapiens neanderthalensis) not available in Ensembl."). I would recommend that you check out our tutorials (https://compomics.com/bioinformatics-for-proteomics/) for how to set up your database.

Secondly, you seem to be having memory issues ("PeptideShaker is encountering memory issues!"). Please see http://compomics.github.io/compomics-utilities/wiki/javatroubleshooting.html#memory-issues for details on how to fix this. In PeptideShaker the memory setting can be changed from the Welcome dialog > Settings & Help > Settings > Java Settings. Please also ensure that you are using a 64 bit Java version.

Best regards,
Harald

**Comment by StullenBrot** [comment] 2016-11-04 13:41
Thanks for helping. I adjusted the memory that can be used. The log file is here:

> 
> Thu Nov 03 09:22:50 CET 2016: PeptideShaker version 1.13.6.
> Memory given to the Java virtual machine: 954728448.
> Total amount of memory in the Java virtual machine: 163053568.
> Free memory: 129518688.
> Java version: 1.8.0_101.
> 1714 script command tokens
> (C) 2009 Jmol Development
> Jmol Version: 12.0.43  2011-05-03 14:21
> java.vendor: Oracle Corporation
> java.version: 1.8.0_101
> os.name: Windows 10
> memory: 51.7/163.1
> processors available: 4
> useCommandThread: false
> 
> 
> Thu Nov 03 09:23:39 CET 2016: PeptideShaker version 1.13.6.
> Memory given to the Java virtual machine: 954728448.
> Total amount of memory in the Java virtual machine: 163053568.
> Free memory: 129655704.
> Java version: 1.8.0_101.
> 1714 script command tokens
> (C) 2009 Jmol Development
> Jmol Version: 12.0.43  2011-05-03 14:21
> java.vendor: Oracle Corporation
> java.version: 1.8.0_101
> os.name: Windows 10
> memory: 52.6/163.1
> processors available: 4
> useCommandThread: false
> java.lang.NullPointerException
> 	at com.compomics.util.db.ObjectsCache.addObject(ObjectsCache.java:299)
> 	at com.compomics.util.db.ObjectsDB.retrieveObjectSynchronized(ObjectsDB.java:878)
> 	at com.compomics.util.db.ObjectsDB.retrieveObject(ObjectsDB.java:799)
> 	at com.compomics.util.db.ObjectsDB.retrieveObject(ObjectsDB.java:761)
> 	at com.compomics.util.experiment.identification.IdentificationDB.getAssumptions(IdentificationDB.java:434)
> 	at com.compomics.util.experiment.identification.Identification.getAssumptions(Identification.java:985)
> 	at com.compomics.util.experiment.identification.Identification.getAssumptions(Identification.java:1005)
> 	at eu.isas.peptideshaker.fileimport.PsmImporter.importAssumptions(PsmImporter.java:699)
> 	at eu.isas.peptideshaker.fileimport.PsmImporter.importPsm(PsmImporter.java:422)
> 	at eu.isas.peptideshaker.fileimport.PsmImporter.access$000(PsmImporter.java:68)
> 	at eu.isas.peptideshaker.fileimport.PsmImporter$PsmImporterRunnable.run(PsmImporter.java:1473)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
> 	at java.util.concurrent.FutureTask.run(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.lang.Thread.run(Unknown Source)
> 
> 
> Fri Nov 04 14:38:46 CET 2016: PeptideShaker version 1.13.6.
> Memory given to the Java virtual machine: 954728448.
> Total amount of memory in the Java virtual machine: 163053568.
> Free memory: 129673800.
> Java version: 1.8.0_111.
> 1714 script command tokens
> (C) 2009 Jmol Development
> Jmol Version: 12.0.43  2011-05-03 14:21
> java.vendor: Oracle Corporation
> java.version: 1.8.0_111
> os.name: Windows 10
> memory: 52.5/163.1
> processors available: 4
> useCommandThread: false
> 
> 
> Command line: 
> "C:\Program Files\Java\jre1.8.0_111\bin\java" -splash:resources\conf\peptide-shaker-splash.png -Xms128M -Xmx4128M -cp "C:\Users\Dennis\Downloads\PeptideShaker-1.10.1\PeptideShaker-1.13.6\PeptideShaker-1.13.6.jar" eu.isas.peptideshaker.gui.PeptideShakerGUI 
> 
> 
> 
> Fri Nov 04 14:39:14 CET 2016: PeptideShaker version 1.13.6.
> Memory given to the Java virtual machine: 3847749632.
> Total amount of memory in the Java virtual machine: 163053568.
> Free memory: 129604472.
> Java version: 1.8.0_111.
> 1714 script command tokens
> (C) 2009 Jmol Development
> Jmol Version: 12.0.43  2011-05-03 14:21
> java.vendor: Oracle Corporation
> java.version: 1.8.0_111
> os.name: Windows 10
> memory: 52.0/163.1
> processors available: 4
> useCommandThread: false
>

**Comment by hbarsnes** [comment] 2016-11-06 21:05
Hi Dennis,

Thanks for the log file. I'm afraid it does not tell me much though. Would it be possible for you to share the files you are trying to load in PeptideShaker? Then I can try to reproduce the error on my side?

Best regards,
Harald

**Comment by StullenBrot** [comment] 2016-11-14 13:38
Hey,

sorry for the late response but I uploaded the SearchGUI file now. I packed it again. Password is 'bbz'.

Thank you

**Comment by hbarsnes** [comment] 2016-11-14 13:59
Hi Dennis,

Thanks for the files. However, to load the data I also need the FASTA and mgf files.

Best regards,
Harald

**Comment by StullenBrot** [comment] 2016-11-14 14:08
I also uploaded those.

mgfs: (pw: 'bbz')
http://www65.zippyshare.com/v/FHVbIocs/file.html

Fasta:
http://www92.zippyshare.com/v/xVhl70P3/file.html

Thank you
Dennis

**Comment by hbarsnes** [comment] 2016-11-14 14:34
Hi again,

You sure you sent me the correct mgf files? As the spectrum titles don't match what is in the identification files:

> Spectrum 'SF21_CIDexcl_C1.53.53.3 File:"SF21_CIDexcl_C1.RAW", NativeID:"controllerType=0 controllerNumber=1 scan=53"' not found in file SF21_CIDexcl_C1.mgf.

Best regards,
Harald

**Comment by StullenBrot** [comment] 2016-11-14 14:36
Hm that would be the .raw files then. When I find something where I can upload the data I will send a link again.

**Comment by hbarsnes** [comment] 2016-11-14 14:46
> Hm that would be the .raw files then. When I find something where I can upload the data I will send a link again.

I don't need the raw files. Only the mgf files used in SearchGUI so that the spectrum title are the identical.

**Comment by StullenBrot** [comment] 2016-11-14 14:50
But I guess I used the raw files in SearchGUI since it is also written in the fiel description you posted!? The .mgf files are from the same sample but do not seem useable here.
Raw files are here: (packed again)
https://www.transfernow.net/865f02v9rw9z

**Comment by hbarsnes** [comment] 2016-11-14 14:53
> But I guess I used the raw files in SearchGUI since it is also written in the fiel description you posted!?

Even if you used the raw files as input to SearchGUI you should still have the mgf files as converted from the raw files, as this is what is used as input to the search engines and then later to PeptideShaker. Where did the mgf files to sent me come from? And don't you have an additional set of mgf files that you use when trying to load the data in PeptideShaker?

**Comment by StullenBrot** [comment] 2016-11-14 14:57
> Even if you used the raw files as input to SearchGUI you should still have the mgf files as converted from the raw files, as this is what is used as input to the search engines and then later to PeptideShaker. Where did the mgf files to sent me come from? And don't you have an additional set of mgf files that you use when trying to load the data in PeptideShaker?

Then those .mfg files should be the correct ones. I can run the search again to make sure though. I can send that tomorrow.

Thank you for the help. I guess I am making some dumb mistake :/

**Comment by hbarsnes** [comment] 2016-11-14 15:38
I just reprocessed your mgf files with SearchGUI (using X! Tandem only as that was where you got the error) and it all loads fine in PeptideShaker on my side. Maybe you could try rerunning the search and reloading the data in PeptideShaker to see if that helps for you as well?

**Comment by StullenBrot** [comment] 2016-11-15 12:54
Hey,
the new run worked fine. Can't really tell what I did differently this time. But thank you very much for your help!

Dennis

**Comment by hbarsnes** [comment] 2016-11-15 14:24
Hi Dennis,

> the new run worked fine. Can't really tell what I did differently this time. But thank you very much for your help!

Great! I will then close the issue. But please feel free to open a new one if you come across other problems.

Best regards,
Harald

**Closed by hbarsnes** 2016-11-15 14:24 UTC
Labels: help wanted
