### ISSUE TITLE
Poor PTM localization scores reported where a clear ion ladder is present

### ISSUE THREAD

**Issue by Kabir12321** [compomics/peptide-shaker#437] opened 2021-01-21 23:17 UTC
Hey Harald and Marc,

I was trying to find out PTM locations of a user-defined modification in the peptides of a single protein using phosphoRS in Peptideshaker. However, it looks like the score for all the possible sites in a single peptide is equal. This could be due to dividing 100 by the total number of possible modifiable sites. This is quite strange since I ran the same data in another software (using ptmRS) and the probability scores seem more sensible. It would be great if anyone of you could solve this issue. 

Thank you,
Kabir

**Comment by mvaudel** [comment] 2021-01-22 14:36
Hi and thank you for contacting us on this.

What you are observing is similar to what was reported in a recent publication (https://pubmed.ncbi.nlm.nih.gov/31975593/). It seems that our implementation of phosphoRS reports only very confidently localized modification sites. We are working with the authors to find the cause of this and fix it. I will follow-up on this issue when we will have more information.

Apologies that we cannot help more at this stage,

Marc

**Comment by Kabir12321** [comment] 2021-01-22 15:06
Hey Marc,

Thanks for reaching out. That is not a problem at all. However, the kind of study that I am doing has already been done in the past using searchGUI and peptideshaker - "https://www.tandfonline.com/doi/full/10.1080/19420862.2019.1565748". I think I should be able to replicate their results using the same search engine. Moreover, I feel the MS2 data is good enough to assign the modification site. The software does assign a site but the PhosphoRS score doesn't feel right. Additionally, I am not seeing any A score or delta score. Have those features been removed?

![image](https://user-images.githubusercontent.com/77367323/105507565-57ef8a00-5c99-11eb-9cf1-4664f9268f69.png)

I hope I was able to explain my question.

Kabir

**Comment by mvaudel** [comment] 2021-01-24 19:18
Hi again,
Thanks for following-up. You are correct, this does not look right. Would it be possible for you to share the files used to create the project?
Apologies for the inconvenience,
Marc

**Comment by Kabir12321** [comment] 2021-01-29 18:56
Hey Marc,

Thanks for replying back and sorry for the delay in my reply. Unfortunately, it won't be possible for me at this point in time to share the database of the protein. Have you seen this kind of error before?

Thanks,
Kabir

**Comment by mvaudel** [comment] 2021-02-03 20:53
Hi again,

Thanks for letting me know, if this is the same problem as the publication I was mentioning before, I should be able to find an example there. I will let you know as soon as we have an update for you to test.

Thanks for your help,

Marc

**Comment by hbarsnes** [comment] 2023-09-28 14:14
Issue assumed resolved with the release of PeptideShaker v3.0.0. If this is not the case, please let us know and we'll reopen the issue.

**Closed by hbarsnes** 2023-09-28 14:14 UTC
Labels: enhancement
