### ISSUE TITLE
PeptideShaker 2.0.9 import failes (Cannot invoke ... because "spectrumMatch" is null)

### ISSUE THREAD

**Issue by TjorvenH** [compomics/peptide-shaker#436] opened 2021-01-19 09:18 UTC
Dear PeptideShaker team,

after trying the automatic SearchGUI-PeptideShaker pipeline, where the PeptideShaker part failed, I tried to open the SearchGUI results directly in PeptideShaker. However, this does not seem to work either (error message appears after file import is completed and probabilities are computed):

Tue Jan 19 10:07:01 CET 2021        Importing Data Canceled!
Tue Jan 19 10:07:01 CET 2021        An error occurred: Cannot invoke "com.compomics.util.experiment.identification.matches.SpectrumMatch.getPeptideAssumptionsMap()" because "spectrumMatch" is null
Tue Jan 19 10:07:01 CET 2021        Please contact the developers (https://github.com/compomics/peptide-shaker/issues).
Tue Jan 19 10:07:03 CET 2021        An error occurred: null
Tue Jan 19 10:07:03 CET 2021        Please contact the developers (https://github.com/compomics/peptide-shaker/issues).

Any help on this matter would be greatly appreciated!

**Comment by hbarsnes** [comment] 2021-01-19 11:22
Are there any errors when running SearchGUI? In other words, do all the searches complete and the SearchGUI zip file is created?

It would be great if you could share the PeptideShaker log file. You'll find it via the Welcome dialog > Settings & Help > Help > Bug Report.

**Comment by TjorvenH** [comment] 2021-01-19 13:06
Please find the log file attached.

No, SearchGUI itself was running fine (up to the point were PeptideShaker came into the picture) and the zip files were created, which I then tried to open "manually" in PS.


[PeptideShaker 2.0.9 log.txt](https://github.com/compomics/peptide-shaker/files/5836014/PeptideShaker.2.0.9.log.txt)

**Comment by hbarsnes** [comment] 2021-01-19 13:19
There seems to be some strange database issues which I have not seen before. Are you running this on the network drive as well (which maybe caused the SearchGUI issues you reported earlier)?

**Comment by TjorvenH** [comment] 2021-01-19 13:59
It is indeed on the same drive - however, that is not a network drive.
The database is based on a metagenome, was clustered with CD-Hit, and the reverse sequences were generated in SearchGUI.

**Comment by hbarsnes** [comment] 2021-01-19 14:04
Is the dataset very large (spectrum files and/or database)? And would it be possible for you to share the data (basically all of the files you are loading in PeptideShaker, I don't think we'll need to redo the search itself) so that we can try to reproduce the error on our side?

BTW, can I close the SearchGUI issue regarding the network drive?

**Comment by TjorvenH** [comment] 2021-01-19 14:09
The dataset consisted of 10 raw files with about 300 Mb each; the database has about 4.8 Gb without and 10.2 Gb with reverse sequences - maybe that's the reason?

Yes, thank you!

**Comment by hbarsnes** [comment] 2021-01-19 15:06
> The dataset consisted of 10 raw files with about 300 Mb each; the database has about 4.8 Gb without and 10.2 Gb with reverse sequences - maybe that's the reason?

Aha, yes, that might be the case. Our software has not been optimized for databases that are this big. In most cases one would need more specialized setups to deal with this type of data. We may be looking into this in the future, but I cannot guarantee it. I know that more and more users are trying our software on these types of data though, so we'll hopefully we'll get to it at some point.

Thanks for sharing the data. However, I'm afraid I do not I have the computing resources required to process it at the moment. When asking for the data I was not expecting it to be that large. :)

Would it be OK if I share the link with the other PeptideShaker developers in case one of them has the required resources available?

**Comment by TjorvenH** [comment] 2021-01-19 15:12
Ok, thank you! So I'll hope for future developments then :)

Yes, sure, that's fine, thanks for asking!

**Comment by CarlosHorro** [comment] 2021-01-22 11:56
Hi @TjorvenH ,

I have a Mac machine with enough memory (64gb) to run PS with your dataset. I was able to analyse it successfully when assigning more memory (both initial and maximum) to the JVM, as:

`java -Xms64G -Xmx64G -cp PeptideShaker-2.0.9.jar eu.isas.peptideshaker.gui.PeptideShakerGUI
`

Looking into your log file, it seems that a maximum of 50gb was set but the initial memory assigned to the JVM is very low (134mb). As 1) I've experienced some problems with java increasing its assigned memory dynamically after the process has started, and 2) I could manage your dataset in PS with 64gb with not with 50gb, I would recommend to:

- Set the maximum memory assigned to the JVM to 64gb (-Xmx64gb)
- Set the initial memory assigned to the JVM to 64gb too (-Xms64gb)

(the command line would be like the example I showed above)

Could you try them both and tell me if this configuration works, please?

Greetings,
Carlos

**Comment by TjorvenH** [comment] 2021-01-25 12:22
Thanks a lot! Indeed, increasing the initial and maximum memory worked and I could open the dataset in PeptideShaker.

**Closed** 2021-04-22 08:50 UTC
Labels: help wanted
