### ISSUE TITLE
Problem with reindexing mgfs during protein inference calculation

### ISSUE THREAD

**Issue by tivdnbos** [compomics/peptide-shaker#385] opened 2019-12-12 09:21 UTC
Hi Marc and Harald,

PeptideShaker crashed during the protein inference calculation. Previously, it crashed due to out of memory, but now it has something to do with reindexing of the mgfs.
I attached the log file. 

Best,
Tim
[bug-igc.txt](https://github.com/compomics/peptide-shaker/files/3954884/bug-igc.txt)

**Comment by hbarsnes** [comment] 2019-12-12 15:08
Hi Tim.

The problem is not in the mgf reindexing but rather in the sequence factory.

I would recommend that you try the new beta release as there the sequence factory no longer exists, and thus the problem should no longer exist either. ;)

Best regards.
Harald

**Comment by tivdnbos** [comment] 2019-12-12 18:03
Thanks Harald, but in the new PeptideShaker version I have another issue, which is explained here: https://github.com/compomics/peptide-shaker-2.0-issue-tracker/issues/46 

Best,
Tim

**Comment by hbarsnes** [comment] 2019-12-12 20:17
Hi Tim,

I assumed the two were connected, but I was not sure. :)

In any case, the new version was created to address specifically these types of issues. So as soon as Marc gets the time to look into why the new version is so slow at the given step both issues should be fixed.

Best regards,
Harald

**Comment by hbarsnes** [comment] 2020-11-04 20:59
This issue should hopefully be fixed in the new release that is available now. If not, please let us know by opening a new issue.

**Closed by hbarsnes** 2020-11-04 20:59 UTC
Labels: bug
