### ISSUE TITLE
Progenesis LC-MS export

### ISSUE THREAD

**Issue by Lucky2407** [compomics/peptide-shaker#340] opened 2018-12-08 15:16 UTC
Dear Harald,

Since a while we are experiencing issues with exporting the validated PSMs, Peptides, Proteins text file to import into Progenesis LC-MS label-free quantification software. This is happening with every new version of PeptideShaker software. Could you please help to fix this problem?

Thank you in advance and best,
Laxmikanth
ISAS-Dortmund.

**Comment by Lucky2407** [comment] 2018-12-09 09:13
Dear Harald,


After processing search engine identification results with PeptideShaker, I proceed with Export - Follow up analysis - Progenesis LC-MS - Validated PSMs, Peptides, Proteins - .txt file, which I need to import in Progenesis.
However, when I click this Export button, an error message pops up saying "Error occurred, please contact the developers".


Enclosed you can find the log.txt file.


Best
Laxmikanth.

**Comment by hbarsnes** [comment] 2018-12-12 22:42
Hi Laxmikanth,

Thanks for the log file. Seems to be a problem with the database interaction. I'm not able to reproduce the issue on my side though. Does it happen with all dataset or just this particular one?

And do you know when the issue started occurring? Was there a specific version of PeptideShaker? Or is it more dependent on the dataset?

Best regards,
Harald

**Comment by Lucky2407** [comment] 2018-12-13 08:43
Dear Harald,
 
Thanks for your effort.
I cannot say exactly when it started, but we have this problem for at least a year independent of the PS version and data sets. Some of us tried to open the .cpsx repeatedly (3-4 times or more) and the export worked.
Recently, after processing the data with PS (ver. 1.16.26), first I exported the .txt file for Progenesis (which actually worked w/o any error) and then saved the project.
I am not sure if it works in this way with all PS versions.
 
Best
Laxmikanth

**Comment by hbarsnes** [comment] 2019-11-22 13:49
This issue should hopefully be solved in the new beta releases of SearchGUI and PeptideShaker. Please see https://groups.google.com/forum/#!topic/peptide-shaker/1ecY0IyMOBM for more details.

If the issue still exists in the beta releases, please open a new issue at https://github.com/compomics/peptide-shaker-2.0-issue-tracker/issues.

If the issue has been solved, it would also be great of you could let us know by replying to this original issue and letting us know. :)

**Comment by hbarsnes** [comment] 2020-11-04 21:05
This issue should hopefully be fixed in the new release that is available now. If not, please let us know by opening a new issue.

**Closed by hbarsnes** 2020-11-04 21:05 UTC
Labels: help wanted
