### ISSUE TITLE
 error while loading the identification files: index is not equal to size

### ISSUE THREAD

**Issue by tivdnbos** [compomics/peptide-shaker#267] opened 2017-05-25 09:55 UTC
Hi,

After running SearchGUI 3.2.18 for a sample on X!Tandem, Comet, MS-GF+ and OMSSA, I tried to loaded the searchgui output folder in to PeptideShaker 1.16.9, when the following error occured:

> Thu May 25 11:42:33 CEST 2017        Import process for pyrococcus (Sample: pyrococcus, Replicate: 0)
> 
> Thu May 25 11:42:33 CEST 2017        Importing sequences from pyrococcus3_concatenated_target_decoy.fasta.
> Thu May 25 11:42:35 CEST 2017        FASTA file import completed.
> Thu May 25 11:42:35 CEST 2017        Importing gene mappings.
> Thu May 25 11:42:35 CEST 2017        Establishing local database connection.
> Thu May 25 11:42:37 CEST 2017        Reading identification files.
> Thu May 25 11:42:37 CEST 2017        Parsing Velos005137.comet.pep.xml.
> Thu May 25 11:42:41 CEST 2017        Loading spectra for Velos005137.comet.pep.xml.
> Thu May 25 11:42:41 CEST 2017        Importing Velos005137.mgf
> Thu May 25 11:42:41 CEST 2017        Velos005137.mgf imported.
> 
> Thu May 25 11:42:41 CEST 2017        Importing Data Canceled!
> Thu May 25 11:42:41 CEST 2017        An error occurred while loading the identification files:
> Thu May 25 11:42:41 CEST 2017        Index: 15366, Size: 15365

Any idea what the problem might be?

Thanks, 
Tim

**Comment by hbarsnes** [comment] 2017-05-26 11:47
Hi Tim,

Thanks for telling us about this. Could you send us the PeptideShaker log file? You'll find it via the Welcome dialog > Settings & Help > Help > Bug Report. It will hopefully tell us a bit more about the problem.

Best regards,
Harald

**Comment by tivdnbos** [comment] 2017-05-26 13:31
Hi Harald,

Thanks for the quick response. I'll add the bug report in attachment.

Best, 
Tim
[PeptideShaker 1.16.9 log.txt](https://github.com/compomics/peptide-shaker/files/1031964/PeptideShaker.1.16.9.log.txt)

**Comment by hbarsnes** [comment] 2017-05-28 21:58
Hi Tim,

The problem is related to the indexing of your mgf file. For some reason PeptideShaker assumes that the file Velos005137.mgf has 15365 spectra while you're trying to link a peptide identification to the spectrum at index 15366. Would it be possible for you to make this mgf file available to me so that I can have a closer look at what is going on?

Best regards,
Harald

PS: You are sure that you are using the correct mgf file right? You don't have more than one mgf file with the same name for example..?

**Comment by tivdnbos** [comment] 2017-05-29 07:07
Hi Harald,

It's the only mgf file in the folder. I've send you the file via WeTransfer to Harald.Barsnes@uib.no.

Kind regards, 
Tim

**Comment by hbarsnes** [comment] 2017-05-29 11:38
Hi Tim,

I don't see anything wrong with the mgf file. It contains 15365 spectra as indicated in the index. So the issue must be related to the Comet pep.xml file. Could you make this one available to me as well? The easiest would perhaps be to make all of the SearchGUI output available, plus the FASTA file used, so that we are sure that I'm loading the exact same data as you.

Best regards,
Harald

**Comment by tivdnbos** [comment] 2017-05-29 11:53
Hi Harald,

I've send you the files!

Kind regards,
Tim

**Comment by hbarsnes** [comment] 2017-05-29 12:00
Hi Tim,

Thanks for the files. I can confirm that I'm now able to reproduce the error. I'll look into it and get back to you.

Best regards,
Harald

**Comment by hbarsnes** [comment] 2017-05-29 12:43
Hi Tim,

The problem comes from the way Comet handles the titles in your mgf file as these all contain an extra ^M at the end. Example:

![uncommon line ending](https://cloud.githubusercontent.com/assets/13151214/26550121/961acbe8-447c-11e7-8957-63aee71bbb07.PNG)

I will check with the Comet developers how this can be handled. In the meantime you can use the other search engines as these don't seem to have this problem. Or you can try to clean up your mgf file and redo the search?

BTW, where does the mgf file come from? For example, has it been moved from Windows to Linux or the other way around? Perhaps something like this could explain the issue?

Best regards,
Harald

**Comment by tivdnbos** [comment] 2017-05-29 12:50
Hi Harald, 

It's not an mgf file from myself, but seeing the screenshot it's in DOS format, so running the following command on Linux should do the trick:
`dos2linux file.mgf`
I'll keep you updated!

Best, 
Tim

**Comment by tivdnbos** [comment] 2017-05-29 14:12
Hi Harald, 

After running the command above, SearchGUI (the GUI) will just skip Comet, so I tried using the command line, but there it will keep trying to do the Comet search, so the task doesn't finish.

Best, 
Tim

**Comment by hbarsnes** [comment] 2017-05-29 14:34
Hi Tim,

Perhaps you can try contacting the [Comet developers](http://groups.google.com/group/comet-ms) directly to see if they have a fix for this issue? As we can always try to add a workaround, but ultimately it comes down to how Comet parses the titles in the first place I think?

Best regards,
Harald

PS: I'm on the Comet list, so I will respond there if they need any input from me as well.

**Comment by hbarsnes** [comment] 2017-05-30 11:35
Fixed with help from the Comet Google Group: https://groups.google.com/forum/#!topic/comet-ms/PiltVrQyDL0.

**Closed by hbarsnes** 2017-05-30 11:35 UTC
Labels: bug
