### ISSUE TITLE
Memory issue with Peptide Shaker

### ISSUE THREAD

**Issue by jblakele** [compomics/peptide-shaker#290] opened 2017-11-14 20:56 UTC
Hi,

Peptide shaker is stalling on me due to memory issues on both gui and cli versions. Sometimes it gives me an error, but sometimes the java binary utilization drops to 0% CPU with no error and no progress being made for 12+hours. 

Can you give me a sense of how memory usage scales on Peptide Shaker? 

I have about 16gb of RAM on my computer, but only about 14 GB of RAM is available to be used at any one time. An HPC cluster with much more RAM is available to me, but to go down that route I need a better idea of how much RAM I'm going to need to request. I work on metaproteomes so its a lot of data. To give you an idea. Typically we will have 11 mgf files that are about 800mb to 1.2 GB, a custom sample specific database that is about 70+mb. I am trying to run multiple search engines and use peptide shaker to help me determine which search algorithm or combination of search algorithms to use for my data moving forward. I tried peptide shaker with less identification files and fewer spectra files, but it is still stalling due to memory just later on. Below is an example command and the error I am getting.

I appreciate the help,
Alfredo

E:\PeptideShakerTest>java -Xmx15000M -cp C:\Bioinformatics\PeptideShaker-1.16.14\PeptideShaker-1.16.14.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI -experiment Preterm -sample Baby70Day20 -replicate 1 -identification_files "E:\PeptideShakerTest\20161026_Baby70_Day20_50ug_DF_Orbi_Elite_Full_30K_01.comet.pep.xml, E:\PeptideShakerTest\20161026_Baby70_Day20_50ug_DF_Orbi_Elite_Full_30K_02.comet.pep.xml, E:\PeptideShakerTest\20161026_Baby70_Day20_50ug_DF_Orbi_Elite_Full_30K_03.comet.pep.xml, E:\PeptideShakerTest\20161026_Baby70_Day20_50ug_DF_Orbi_Elite_Full_30K_01.myrimatch.mzid, E:\PeptideShakerTest\20161026_Baby70_Day20_50ug_DF_Orbi_Elite_Full_30K_02.myrimatch.mzid,  E:\PeptideShakerTest\20161026_Baby70_Day20_50ug_DF_Orbi_Elite_Full_30K_03.myrimatch.mzid" -out E:\PeptideShakerTest\out.cpsx -spectrum_files "E:\PeptideShakerTest\20161026_Baby70_Day20_50ug_DF_Orbi_Elite_Full_30K_01.mgf, E:\PeptideShakerTest\20161026_Baby70_Day20_50ug_DF_Orbi_Elite_Full_30K_02.mgf, E:\PeptideShakerTest\20161026_Baby70_Day20_50ug_DF_Orbi_Elite_Full_30K_03.mgf" -id_params E:\PeptideShakerTest\Baby70Day20.par

Tue Nov 14 13:06:44 EST 2017 Match Validation and Quality Control. Please Wait...
10% 20% 30%Exception in thread "pool-19-thread-7" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-20-thread-2"

<CompomicsError>PeptideShaker ran out of memory! See the PeptideShaker log for details.</CompomicsError>
Ran out of memory!
Memory given to the Java virtual machine: 13981188096.
Memory used by the Java virtual machine: 13981188096.
Free memory in the Java virtual machine: 1747938112.
java.lang.NullPointerException

        at eu.isas.peptideshaker.validation.MatchesValidator$PeptideValidatorRunnable.run(MatchesValidator.java:1688)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Tue Nov 14 13:43:29 EST 2017 Ran out of memory!
java.lang.OutOfMemoryError: GC overhead limit exceeded
<CompomicsError>PeptideShaker used up all the memory and had to be stopped. See the PeptideShaker log for details.</CompomicsError>
Ran out of memory!
Memory given to the Java virtual machine: 13981188096.
Memory used by the Java virtual machine: 13981188096.
Free memory in the Java virtual machine: 1748127520.
java.lang.OutOfMemoryError: GC overhead limit exceeded

**Comment by hbarsnes** [comment] 2017-11-15 10:25
Hi Alfredo, 

I'm afraid this is a common problem. The good news is that we are currently refactoring the backend to greatly reduce the memory usage and generally speed up the processing. The bad news is that it will still take some time before this new version becomes available, but we will let you know as soon as a beta version is available for testing.

Best regards,
Harald

**Comment by jblakele** [comment] 2017-11-15 15:55
Hi Harald,


Thank you for the feedback. I look forward to testing a beta version when it is available. In the mean time, do you have a sense for how much memory is being eaten up on the back end? Should it work if I throw 30 GB of memory at it or 100?


Best Regards,

Alfredo

________________________________

**Comment by hbarsnes** [comment] 2017-11-15 22:15
Hi Alfredo,

It's hard to give an estimate of the memory required as it very much depends on the data being processed. And of course in principle the tool should never run out of memory, but simply slow down and depend more on writing/reading to/from the disk. But it seems like an error has been introduced in a recent version where this approach is not always used as intended. This should all be fixed with the upcoming release though. As a general suggestion, I would give it as much memory as you have available and then rather downscale if you see that not all of the memory is being used.

Best regards,
Harald

**Comment by volkyx** [comment] 2018-03-27 03:33
Hi all,

I am having the same problem as well on 1.16.17 and the error is like this "Exception in thread "TimerQueue" java.lang.OutOfMemoryError: GC overhead limit exceeded". I have 16 Gb memory and almost half of it was available during the error. Trying to allocate more memory to the JAVA or JVM did not help as well. So is there any way to solve this error
Best regards
Volkan

**Comment by volkyx** [comment] 2018-03-27 03:41
Ok my bad,

I have changed the java settings from the peptide shaker (Edit>Java settings) to include more ram (it was set to 4096 mb)  than the problem is solved. 

Best.

**Closed** 2019-11-22 13:40 UTC
Labels: bug
