### ISSUE TITLE
An error occurred while loading the identification files - NullPointerException

### ISSUE THREAD

**Issue by danpcampbell** [compomics/peptide-shaker#318] opened 2018-06-24 23:34 UTC
I am getting persistent errors attempting to load data to peptide-shaker.  The below is console output from a recent attempt.   I looked through the troubleshooting list and no progress so far.  What else can I try, or what other information can I provide you?

> 10% 20% 30% 40% 50% 60% 70% 80% 90%<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>
>
>Thu Jun 21 17:13:21 EDT 2018 An error occurred while loading the identification files.
>Thu Jun 21 17:13:21 EDT 2018 Please see the error log (Help Menu > Bug Report) for details.
>java.lang.NullPointerException
>        at eu.isas.peptideshaker.parameters.PSPtmScores.changeRepresentativeSite(PSPtmScores.java:227)
>        at eu.isas.peptideshaker.ptm.PtmScorer.peptideInference(PtmScorer.java:1862)
>        at eu.isas.peptideshaker.PeptideShaker.processIdentifications(PeptideShaker.java:387)
>        at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:547)
>        at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporter.java:151)
>        at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:229)
>        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:738)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:218)
        at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:938)
Free memory: 10275565448
Thu Jun 21 17:13:31 EDT 2018 PeptideShaker Processing Canceled.
\<CompomicsError\>PeptideShaker processing canceled. See the PeptideShaker log for details.\</CompomicsError\>

**Comment by hbarsnes** [comment] 2018-06-25 21:09
Hi.

Thanks for telling us about this. Could you let us know which PTMs that are included in your search? And which search engines you are using?

Would it be possible to share your data with us so that we can try to reproduce the error on our end?

Finally, have you tried changing the [PTM Localization options](https://github.com/compomics/compomics-utilities/wiki/IdentificationParametersCLI#ptm-localization)? For example changing or turning off the PTM scoring? Clearly not a long-term solution, but should allow you to at least load the data while we look for a fix.

Best regards,
Harald

**Comment by danpcampbell** [comment] 2018-06-26 13:12
Thanks for your help, and I look forward to chasing this down with you guys.

Carbamidomethylation of C was chosen as fixed modifications and Oxidation of M as variable modifications. 

We used all 8 search engines.

I can share the data, but the current data set is quite large, about 4GB zipped.  I am working on finding a minimal set that causes the exception but each run takes quite a while, of course, so it is slow going.  Is there a means for me to upload it somewhere?

I have not yet tried changing the PTM Localization options.  I will make an attempt with that today.

**Comment by hbarsnes** [comment] 2018-06-26 13:41
> Carbamidomethylation of C was chosen as fixed modifications and Oxidation of M as variable modifications.

Ok, so no advanced combinations of PTMs then. My best guess is then that it's a consequence of known issues in our backend code related to memory usage. The good news is that we are now getting close to a new beta version that should solve all of these issues. My plan is to try loading your data in this new version to hopefully confirm that the issue is there no longer.

> I can share the data, but the current data set is quite large, about 4GB zipped. I am working on finding a minimal set that causes the exception but each run takes quite a while, of course, so it is slow going. Is there a means for me to upload it somewhere?

I would recommend using a service such as Dropbox.

**Comment by danpcampbell** [comment] 2018-06-26 13:49
I have uploaded to my Google Drive.  I prefer not to post the data completely publicly.  Is there a means to share a link privately with you?

**Comment by hbarsnes** [comment] 2018-06-26 13:57
> I have uploaded to my Google Drive. I prefer not to post the data completely publicly. Is there a means to share a link privately with you?

You can send the link to harald.barsnes at gmail.com

**Comment by danpcampbell** [comment] 2018-06-26 14:04
First round of data sent.  Thank you!

**Comment by hbarsnes** [comment] 2018-06-26 22:19
> First round of data sent.

Zip file downloaded. However, to try to open the data in PeptideShaker I would also need the mgf files and the FASTA file.

**Comment by danpcampbell** [comment] 2018-06-26 23:03
added FASTA and 35 mgf files

**Comment by danpcampbell** [comment] 2018-06-27 14:49
It took a while to run but I wanted to confirm that changing PTM Scoring/Probabilistic Score to "None" and Site Alignment/Confident Sites to "No" allowed the 35 sample data set to load.

**Comment by hbarsnes** [comment] 2018-06-27 15:02
> It took a while to run but I wanted to confirm that changing PTM Scoring/Probabilistic Score to "None" and Site Alignment/Confident Sites to "No" allowed the 35 sample data set to load.

Great! This should be ok for your dataset anyway, as I assume you don't really care all that much about the location of the oxidations. Would be different for a study looking for a particular type of modification.

I will still try to locate the source of the issue though. All your data has been downloaded and I've started the processing in the new upcoming PeptideShaker version. But as you say, it takes a while to load the data. You could consider not using all of the eight search engines btw, as the results tend to not change all that much after going beyond two or three search engines. You can compare the results in the Spectrum IDs tab and get a feel for which search engines that work best for your dataset.

**Comment by danpcampbell** [comment] 2018-06-27 15:23
I am not personally a bioinformatician - I am a computer scientist, working with a bioinformatician.  So there is room for some information loss in the translation, but my collaborator reports: "Percentage oxidation is important for my results though, because I am testing block age/sample degradation during storage."

I made subsets of the data with 9 and 18 of the samples.  Loading the 9 sample case into peptideshaker, with PTM options turned back on succeeded in about 5 minutes.  I am currently attempting to load the 18 sample case.

**Comment by hbarsnes** [comment] 2018-06-27 15:39
The oxidations are still there. The number of oxidations does not change. It just that the tool no longer provides a score for which residue in the peptide the oxidation is on. Which only happens if there is more than one possible location in the same peptide.

**Comment by danpcampbell** [comment] 2018-06-27 15:40
by the way, 18 sample subset loaded in ~12 minutes.  I'll try 27 next.  Trying to find a minimum set that fails.

**Comment by danpcampbell** [comment] 2018-06-30 16:11
I have a minimum failing set, which fails reliably within a couple of hours.  If you were able to load my data into the upcoming version, then I would guess this is not helpful, but if it will help your debugging efforts, please let me know.

my collaborator is re-considering the study's plan and may end up with paths that do not trigger this issue, but I would like to ensure that our experience can help your development and debugging efforts as much possible.

**Comment by hbarsnes** [comment] 2018-06-30 17:40
> I have a minimum failing set, which fails reliably within a couple of hours. If you were able to load my data into the upcoming version, then I would guess this is not helpful, but if it will help your debugging efforts, please let me know.

Thanks for the detailed testing! I tried loading your data in the new upcoming version, but it uncovered an unrelated issue that we are still trying to solve. So we do not yet know if the problem you experience in the current PeptideShaker version has been corrected or not. Knowing the minimum failing set would be great for the future tests though.

**Comment by danpcampbell** [comment] 2018-06-30 21:41
I have uploaded a new searchgui.zip with 21 of the samples.  This one fails on my desktop, reliably, within a couple of hours.

**Comment by wetzelmirage** [comment] 2018-07-25 22:59
Hello there,

I think I have a similar problem and I cannot get things working. Any solutions? I am running a bit desperate now. Here are the logs: 
[PeptideShaker report.txt](https://github.com/compomics/peptide-shaker/files/2229809/PeptideShaker.report.txt)
[PeptideShaker 1.16.26 log.txt](https://github.com/compomics/peptide-shaker/files/2229810/PeptideShaker.1.16.26.log.txt)

Thanks, .

**Comment by hbarsnes** [comment] 2018-08-05 08:48
@wetzelmirage I'm afraid the new major PeptideShaker release which fixes these issues is still in development. But a beta version should hopefully be available for testing within not too long. We'll keep you posted.

**Comment by hbarsnes** [comment] 2019-11-22 13:49
This issue should hopefully be solved in the new beta releases of SearchGUI and PeptideShaker. Please see https://groups.google.com/forum/#!topic/peptide-shaker/1ecY0IyMOBM for more details.

If the issue still exists in the beta releases, please open a new issue at https://github.com/compomics/peptide-shaker-2.0-issue-tracker/issues.

If the issue has been solved, it would also be great of you could let us know by replying to this original issue and letting us know. :)

**Comment by hbarsnes** [comment] 2020-11-04 21:06
This issue should hopefully be fixed in the new release that is available now. If not, please let us know by opening a new issue.

**Closed by hbarsnes** 2020-11-04 21:06 UTC
Labels: bug
