### ISSUE TITLE
Phosphosite Localization using PhosphoRS

### ISSUE THREAD

**Issue by wenbostar** [compomics/peptide-shaker#137] opened 2016-02-11 06:00 UTC
Hi Harald,
I have tried to use SearchGUI and PeptideShaker to analyze a phosphoproteomic data (http://www.ebi.ac.uk/pride/archive/projects/PXD001792, file:1_QEp2_LC11_SeHu_LivPhos_EarlyInsulin_10s_Bio1.raw).

Below is the command line to generate parameter file by using SearchGUI:

`/home/test/jdk1.8.0_60/jre/bin/java -Djava.awt.headless=true -cp /home/test/SearchGUI-2.6.3.jar eu.isas.searchgui.cmd.IdentificationParametersCLI -out search_new.par -variable_mods "Phosphorylation of S,Phosphorylation of Y,Phosphorylation of T,Oxidation of M" -fixed_mods "Carbamidomethylation of C" -db mouse_concatenated_target_decoy.fasta -prec_tol 10 -frag_tol 0.05 -max_charge 5 -max_isotope 1 -xtandem_refine 0 -xtandem_evalue 30 -myrimatch_max_pep_length 45 -myrimatch_num_matches 1 -myrimatch_num_ptms 3 -myrimatch_fragmentation cid -comet_num_matches 1 -comet_max_frag_charge 5 -useGeneMapping 0 -updateGeneMapping 0 -annotation_level 0.98 -import_peptide_length_min 7 -import_peptide_length_max 45 -ptm_score 1 -score_neutral_losses 0 -db_pi mouse_concatenated_target_decoy.fasta -psm_fdr 0.01 -peptide_fdr 0.01 -protein_fdr 0.01 -msgf_instrument 3 -msgf_fragmentation 3 -msgf_protocol 1 -msgf_min_pep_length 7 -msgf_max_pep_length 45 -msgf_num_matches 1 -msgf_additional 1 -msgf_termini 2 -msgf_num_ptms 3
`

Below is the command line of PeptideShaker 

`java -Xmx60G -cp  /home/test/PeptideShaker-1.7.4.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI -experiment phos -sample phos -replicate 1 -identification_files /home/test/searchgui_3se_result/searchgui_out.zip -out  /home/test/my_3se.cpsx -spectrum_files /home/test/phos1.mgf -id_params /home/test/search_new.par -temp_folder /home/test/tmmmp`

However, the result of phosphosite scoring is weird. Below is the PSM report file:
[phos_phos_1_Default_PSM_Report.txt.tar.gz](https://github.com/compomics/peptide-shaker/files/125938/phos_phos_1_Default_PSM_Report.txt.tar.gz)

Could you please take a look at this file?

Best regards!
Bo

**Comment by hbarsnes** [comment] 2016-02-11 10:26
Hi Bo,

I'm not sure what you find "weird" with the phosphosite scoring? I just had a quick look at your PSM export and it seems ok to me. Do you have an example?

Best regards,
Harald

**Comment by wenbostar** [comment] 2016-02-11 10:59
Hi Harald,
Thanks a lot. Below is part context of the PSM report file.
![phos](https://cloud.githubusercontent.com/assets/5302110/12974770/76a7ed18-d0f1-11e5-813f-5411671dfeb9.PNG)
You can see that almost all of the sites have the same score.
Best regards!
Bo

**Comment by hbarsnes** [comment] 2016-02-11 11:12
Hi Bo,

Ah, yes, I see what you mean. This is indeed strange. I will look into it and get back to you.

Best regards,
Harald

**Comment by mvaudel** [comment] 2016-02-11 16:19
Dear Bo,

it seems that all you sites give equal scores. This happens when PhosphoRS does not find any site determining peaks. The fact that it happens on every spectrum is very suspicious and indicates a problem in the scoring. My best guess is that the spectra are not properly annotated. Would it be possible for you to export the project as zip file and send it to us? We should be able to diagnose what went wrong :)

Best regards,

Marc

**Comment by wenbostar** [comment] 2016-02-12 06:46
Hi Marc,
Thanks a lot. Below is the link of the cpsx file generated by PeptideShaker:
https://www.dropbox.com/s/c5bknxrvrmlsqix/my_3se.cpsx.tar.gz?dl=0
MGF file: https://www.dropbox.com/s/ijv128t89ete14v/phos1.mgf.tar.gz?dl=0

Best regards!
Bo

**Comment by mvaudel** [comment] 2016-02-12 09:23
Hi again,

Can you include your fasta file as well? Alternatively, go to the "Export" -> "PeptideShaker Project As" -> "Zip File" menu.

Thanks,

Marc

**Comment by wenbostar** [comment] 2016-02-12 10:45
Hi Marc,
OK. Please find the fasta file here :https://www.dropbox.com/s/ob8faxuozgv0zkt/mouse_concatenated_target_decoy.fasta.tar.gz?dl=0

Best regards!
Bo

**Comment by mvaudel** [comment] 2016-02-12 17:11
Hi again,

It seems that the problem is that you set 98% in the intensity limit for the spectrum annotation. Is there any reason why not use the default value? This way, only the 2% most intense peaks will be annotated while reducing this threshold allows annotating more peaks (see attachment).

Due to the fact that so few peaks were annotated, only PhosphoRS did not find any site determining ions and all sites received the same probability. This is also the reason why all matches were marked as doubtful.

I would recommend to create the project again leaving the advanced settings to default, you should see more relevant scores.

Hope this helps,

Marc

**Comment by mvaudel** [comment] 2016-02-12 17:17
As a side comment, it seems that you are using an FDR threshold of 0.01 %, looks like a typo :)

**Comment by wenbostar** [comment] 2016-02-13 01:40
Hi Marc,
Thanks a lot. Below is the description of function "setIntensityLimit". According to this description, 0.75 means that only the 75% most intense peaks are considered for annotations. So I thought that 0.98 means that the 98% most intense peaks are considered for annotations. Is my understanding not correct?

/**
     * Sets the annotation level. [0.0 - 1.0], where 0.0 means that all peaks
     * are considered for annotations, while 0.75 means that only the 75% most
     * intense peaks are considered for annotations.
     *
     * @param intensityLimit the intensityLimit to set
     */
    public void setIntensityLimit(double intensityLimit) {
        this.intensityLimit = intensityLimit;
    }

Best regards!
Bo

**Comment by wenbostar** [comment] 2016-02-13 01:52
Hi Marc,

Thanks again.

>>As a side comment, it seems that you are using an FDR threshold of 0.01 %, looks like a typo :)

I wanted to set the FDR (PSM, peptide and protein levels) as 1%. Below is the command line to generate parameter file by using SearchGUI. You mean that the setting is not correct?
`
/home/test/jdk1.8.0_60/jre/bin/java -Djava.awt.headless=true -cp /home/test/SearchGUI-2.6.3.jar eu.isas.searchgui.cmd.IdentificationParametersCLI -out search_new.par -variable_mods "Phosphorylation of S,Phosphorylation of Y,Phosphorylation of T,Oxidation of M" -fixed_mods "Carbamidomethylation of C" -db mouse_concatenated_target_decoy.fasta -prec_tol 10 -frag_tol 0.05 -max_charge 5 -max_isotope 1 -xtandem_refine 0 -xtandem_evalue 30 -myrimatch_max_pep_length 45 -myrimatch_num_matches 1 -myrimatch_num_ptms 3 -myrimatch_fragmentation cid -comet_num_matches 1 -comet_max_frag_charge 5 -useGeneMapping 0 -updateGeneMapping 0 -annotation_level 0.98 -import_peptide_length_min 7 -import_peptide_length_max 45 -ptm_score 1 -score_neutral_losses 0 -db_pi mouse_concatenated_target_decoy.fasta -psm_fdr 0.01 -peptide_fdr 0.01 -protein_fdr 0.01 -msgf_instrument 3 -msgf_fragmentation 3 -msgf_protocol 1 -msgf_min_pep_length 7 -msgf_max_pep_length 45 -msgf_num_matches 1 -msgf_additional 1 -msgf_termini 2 -msgf_num_ptms 3
`

Best regards!
Bo

**Comment by wenbostar** [comment] 2016-02-13 04:49
Hi Marc,
If I set the value of "-annotation_level" as 0.75 or lower, as for the phosphosite scoring result, I got the similar result with before. Is it the same in your side?
Best regards!
Bo

**Comment by mvaudel** [comment] 2016-02-13 11:07
Hi Bo,

Sorry that the documentation is unclear, I will correct it. 0.0 means all
peaks are annotated. 75% means the peaks higher than the 75% most intense
peak, so the 25% most intense peaks ;)

Best regards,

Marc

2016-02-13 2:40 GMT+01:00 wenbostar <notifications@github.com>:

**Comment by mvaudel** [comment] 2016-02-13 11:09
Hi Bo,

Yes, the FDR is given in percent. If you open your project you will see in
the validation tab that it tried to validate at 0.01%. You might want to
try -psm_fdr 1 -peptide_fdr 1 -protein_fdr 1 or just leave to default :)
Then there will be a lot more green on the interface!

Best regards,

Marc

2016-02-13 2:52 GMT+01:00 wenbostar <notifications@github.com>:

**Comment by mvaudel** [comment] 2016-02-13 11:10
Hi again,

I don't have the search engine results, so I cannot reproduce the problem.
Can you send them to me?

Best regards,

Marc

2016-02-13 5:49 GMT+01:00 wenbostar <notifications@github.com>:

**Comment by wenbostar** [comment] 2016-02-13 12:50
Hi Marc,
Thanks again. Below is the link of search engine result:
https://www.dropbox.com/s/v3xd5ufgggsrs10/searchgui_out.zip?dl=0
Best regards!
Bo

**Comment by mvaudel** [comment] 2016-02-15 08:29
Hi Bo,

Many thanks for the files, I have been able to reproduce the problem (all
sites get the same score). There is nothing obvious on why this happens, I
will look into the scoring in details later today or tomorrow and come back
to you.

Apologies for the inconvenience,

Marc

2016-02-13 13:50 GMT+01:00 wenbostar <notifications@github.com>:

**Comment by wenbostar** [comment] 2016-02-17 16:22
Hi Marc,
Do you konw how to fix the problem? Thanks for your wonderful work.
Best regards!
Bo

**Comment by mvaudel** [comment] 2016-02-18 08:32
Hi Bo,

Sorry I have been in meetings all week so could not look at the code, and
am afraid it is not going to get any better until tomorrow afternoon...
Then I can actually start working again and will keep you posted with my
progress :)

Best regards,

Marc

2016-02-17 17:22 GMT+01:00 wenbostar <notifications@github.com>:

**Comment by mvaudel** [comment] 2016-02-19 17:56
Hi Bo,

It took some time but I think I have found the problem: the number of decimals used in our PhosphoRS probabilities calculation was not enough for high resolution/spectra with few peaks. Using more decimals solved the problem but now the calculation is taking ages. I will fine tune this and hopefully come back to you with a solution next week.

Best regards,

Marc

**Comment by mvaudel** [comment] 2016-02-20 15:38
Dear Bo,

Can you try the beta version available at the link below and see if the PTM scoring is working as expected?

http://vedlegg.uib.no/?id=7390dc7cf59bb29713d9873c7dfacab4

Best regards,

Marc

**Comment by wenbostar** [comment] 2016-02-21 05:07
Hi Marc,
Thank you very much. I have tested the new version (1.8.0-beta), however it didn't work. Below is the error message:

Sun Feb 21 12:56:33 CST 2016 Computing PSM probabilities.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Sun Feb 21 12:56:33 CST 2016 Scoring PTMs in PSMs (D-score and PhosphoRS)
Sun Feb 21 12:56:33 CST 2016 Scoring PSM PTMs. Please Wait...
java.lang.IllegalArgumentException: PhosphoRS probability > 1.
        at com.compomics.util.experiment.identification.ptm.ptmscores.PhosphoRS.getSequenceProbabilities(PhosphoRS.java:248)
        at eu.isas.peptideshaker.ptm.PtmScorer.attachProbabilisticScore(PtmScorer.java:320)
        at eu.isas.peptideshaker.ptm.PtmScorer.scorePTMs(PtmScorer.java:419)
        at eu.isas.peptideshaker.ptm.PtmScorer$PsmPtmScorerRunnable.run(PtmScorer.java:2373)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Best regards!
Bo

**Comment by mvaudel** [comment] 2016-02-21 19:34
Hi Bo,

Thank you for the testing. This is a rounding issue in the cumulative
probability estimation. I will try to find a way around this problem
tomorrow.

Best regards,

Marc

2016-02-21 6:07 GMT+01:00 wenbostar <notifications@github.com>:

**Comment by mvaudel** [comment] 2016-02-24 12:27
Hi again,

Sorry about going back and forth on this one. Can you check that this
version works properly on your side?

http://vedlegg.uib.no/?id=19a97badc9b699f16131d46795b9070c


Best regards,

Marc



2016-02-21 20:34 GMT+01:00 Marc Vaudel <mvaudel@gmail.com>:

**Comment by wenbostar** [comment] 2016-02-25 13:00
Hi Marc,
Thank you so much. It works now. But the used memory for a mzid file with the size ~ 50M is about 3G when the phosphoRS scoring is running. Do you have any method to reduce the memory?
Best regards!
Bo

**Comment by mvaudel** [comment] 2016-02-25 13:15
Hi Bo,

The memory needed is mainly used to cache data. If you give less to the
tool, it will use less but will need more time. As far as I tested most of
the memory is required during peptide to protein mapping, and we are
working on reducing this :)

Best regards,

Marc

2016-02-25 14:00 GMT+01:00 wenbostar <notifications@github.com>:

**Comment by wenbostar** [comment] 2016-02-26 15:18
Hi Marc,
Got it. Thank you very much.
Best regards!
Bo

**Comment by hbarsnes** [comment] 2016-02-29 20:14
Hi Bo,

The PhosphoRS issue should be fixed in PeptideShaker v1.8.0.

Best regards,
Harald

**Closed by hbarsnes** 2016-02-29 20:14 UTC
Labels: help wanted

**Comment by wenbostar** [comment] 2016-03-01 09:57
Hi Harald and Marc,
Thank you all for your excellent work.
Best regards!
Bo
