### ISSUE TITLE
Error when Importing Data

### ISSUE THREAD

**Issue by waikokc** [compomics/peptide-shaker#187] opened 2016-06-30 08:31 UTC
Dear developer,

I encountered some problems while using the PeptideShaker tool.
i have comet, xtandem and mgsf search results obtained by searchGui.
Peptideshaker showed "Importing Data Canceled"  message when import the comet search result.
when i try to use xtandem and mgsf search result import to peptideshaker ,is fine.
but only the comet search result have problems.

Thanks
waikok

error message:
"
Thu Jun 30 16:15:53 CST 2016: PeptideShaker version 1.12.1.
Memory given to the Java virtual machine: 15934685184.
Total amount of memory in the Java virtual machine: 163053568.
Free memory: 127913432.
Java version: 1.8.0_91.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 1.8.0_91
os.name: Windows 7
memory: 51.5/163.1
processors available: 8
useCommandThread: false
<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>
java.lang.IndexOutOfBoundsException: Index: 86081, Size: 86081
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.compomics.util.experiment.io.massspectrometry.MgfIndex.getSpectrumTitle(MgfIndex.java:239)
	at com.compomics.util.experiment.massspectrometry.SpectrumFactory.getSpectrumTitle(SpectrumFactory.java:992)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importSpectrum(FileImporter.java:1012)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importPsms(FileImporter.java:730)
at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:485)
at
eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.doInBackground(FileImporter.java:439)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

"

**Comment by hbarsnes** [comment] 2016-07-02 10:12
Hi Waikok,

Thanks for telling us about this. Would it be possible for you to make the Comet search results available to us (including the fasta and mgf files)? Then we'll try to reproduce the error on our side and hopefully locate the problem.

Best regards,
Harald

**Comment by waikokc** [comment] 2016-07-05 07:38
Hi Harald,

Ok, This is the files about  "Importing Data Canceled" message when using peptideshaker.

MGF-
https://drive.google.com/open?id=0B09qOhMHMUBKcGc3NHdLT3M0bDA
Fasta-
https://drive.google.com/open?id=0B09qOhMHMUBKV2JDVy1EZW1LdHc
Search result-
https://drive.google.com/open?id=0B09qOhMHMUBKSTlmYXkwdlNuOUk

Thanks.

Waikok

**Comment by hbarsnes** [comment] 2016-07-05 11:04
Hi Waikok,

Thanks for the files. The problem is in the generation of the Comet pepxml file and is related to the parsing of the spectrum titles in the mgf file.

For example:
`TITLE=File: "G:\FusionData\DIARaw\Hela1ug_QC_Middle_DDA_150226_01_150227005127.raw"; SpectrumID: "2"; scans: "5"`

ends up as:
`spectrum="Hela1ug_QC_Middle_DDA_150226_01_150227005127.00005.00005.3spectrumNativeID_FusionDataDIARawHela1ug_QC_Middle_DDA_150226_01_150227005127raw_SpectrumID_2scans5"`

in the pepxml file.

While it should be:
`spectrum="test.00005.00005.3" spectrumNativeID="File: &quot;G:\FusionData\DIARaw\Hela1ug_QC_Middle_DDA_150226_01_150227005127.raw&quot;; SpectrumID: &quot;2&quot;; scans: &quot;5&quot;"`

(`&quot;` is just the escaping of the quote characters.)

The strange thing is that on my side I get the correct second version...

Which version of SearchGUI are you using? And are you using the Comet version included in SearchGUI or a separate download? From the paths in the shared files I assume that you use Windows right? I've tested both the 32 and 64 bit Comet version on Windows and both generate the correct spectrum title line in the pepxml file when using the current release of SearchGUI.

I'd recommend updating to the latest version of SearchGUI and see if that solves the problem.

Best regards,
Harald

**Comment by waikokc** [comment] 2016-07-06 05:26
Hi Harald,

i use SearchGui  version 3.0.2. and peptideShaker version 1.12.1, then re-run the data, but still show "Importing Data Canceled" message . (i use window,64bit)

searchgui result:
(zip): https://drive.google.com/open?id=0B09qOhMHMUBKMkV6TTBRd1ZXQVk
(html): https://drive.google.com/open?id=0B09qOhMHMUBKR2kybDlYTWx0eHc

peptideshaker log :
https://drive.google.com/open?id=0B09qOhMHMUBKOVNFRzlhdnd4OTA

Thanks


waikok

**Comment by hbarsnes** [comment] 2016-07-06 11:44
Hi Waikok,

Thanks for the files. Your pepxml file now seems to be ok, but there is another issue stopping the data from being loaded. I can confirm that I get the same error as the one you're having, so I will dig deeper and see if I can locate and fix the problem. I'll let you know as soon as I've come up with a fix.

Best regards,
Harald

**Comment by hbarsnes** [comment] 2016-07-06 22:42
Hi Waikok,

How did you generate the mgf file? Was Linux or Mac used? As there are some strange line endings for some of the title lines causing the problem. The only time I've seen this before is when a file was created on Linux and then moved to Windows (or the other way around) for processing. Is something like this the case for your mgf file? The strange thing here is that is only happens for some of the titles and not all of them. That part I don't understand...

Best regards,
Harald

**Comment by waikokc** [comment] 2016-07-07 04:47
Hi Harald,

The mgf generated by Proteome Discoverery (software,windows).
I think i will only use the xtandem and msgf+ search result to run the Peptideshaker.
Thank you for all your assistance.

Waikok

**Comment by hbarsnes** [comment] 2016-07-07 16:44
Hi Waikok,

The issue should be fixed in PeptideShaker v1.12.2. If this is not the case, please let us know and we'll reopen the issue.

Best regards,
Harald

**Closed by hbarsnes** 2016-07-07 16:44 UTC
Labels: bug
